/**
 * Award/Handoff Data Access Layer
 *
 * All award/handoff reads/writes go through these functions.
 */

import * as db from './json-db'
import type { AwardHandoff } from '@/types/commercial'

const COLLECTION = 'award_handoffs' as const

/** Generate a human-readable reference ID: AWD-0001 through AWD-9999 */
export function generateReferenceId(): string {
  const all = db.list<AwardHandoff>(COLLECTION)
  const maxNum = all.reduce((max, a) => {
    const match = a.reference_id.match(/^AWD-(\d+)$/)
    const num = match ? parseInt(match[1]!, 10) : 0
    return Math.max(max, num)
  }, 0)
  return `AWD-${String(maxNum + 1).padStart(4, '0')}`
}

/** Get a single award/handoff by ID. */
export function getAwardHandoff(id: string): AwardHandoff | undefined {
  return db.getById<AwardHandoff>(COLLECTION, id)
}

/** List all non-archived award/handoffs. */
export function listAwardHandoffs(): AwardHandoff[] {
  return db.list<AwardHandoff>(COLLECTION)
}

/** List award/handoffs for a specific client. */
export function listAwardHandoffsByClient(clientId: string): AwardHandoff[] {
  return db.query<AwardHandoff>(COLLECTION, {
    linked_client_id: clientId,
  } as db.QueryFilter<AwardHandoff>)
}

/** List award/handoffs for a specific proposal. */
export function listAwardHandoffsByProposal(proposalId: string): AwardHandoff[] {
  return db.query<AwardHandoff>(COLLECTION, {
    linked_proposal_id: proposalId,
  } as db.QueryFilter<AwardHandoff>)
}

/** Create a new award/handoff. Generates reference_id and sets initial status. */
export function createAwardHandoff(
  data: Omit<AwardHandoff, db.AutoGeneratedKeys | db.DefaultableKeys | 'reference_id' | 'status' | 'created_project_id'>
    & Partial<Pick<AwardHandoff, db.DefaultableKeys & keyof AwardHandoff>>
    & { created_project_id?: string | null },
  actorId: string,
): AwardHandoff {
  const reference_id = generateReferenceId()
  return db.create<AwardHandoff>(
    COLLECTION,
    {
      ...data,
      reference_id,
      status: 'awarded_intake_open',
      created_project_id: data.created_project_id ?? null,
    } as Omit<AwardHandoff, db.AutoGeneratedKeys>,
    actorId,
  )
}

/** Update an existing award/handoff. */
export function updateAwardHandoff(
  id: string,
  changes: Partial<Omit<AwardHandoff, keyof db.BaseEntity>>,
  actorId: string,
  reason?: string,
): AwardHandoff {
  return db.update<AwardHandoff>(COLLECTION, id, changes, actorId, reason)
}

/** Soft-delete an award/handoff. */
export function archiveAwardHandoff(id: string, actorId: string, reason: string): void {
  db.softDelete(COLLECTION, id, actorId, reason)
}

/** Get audit log for a specific award/handoff. */
export function getAwardHandoffAuditLog(awardHandoffId: string) {
  return db.getAuditLog(COLLECTION, awardHandoffId)
}
