/**
 * Change Order Data Access Layer
 *
 * All change order reads/writes go through these functions.
 */

import * as db from './json-db'
import type { ChangeOrder } from '@/types/commercial'

const COLLECTION = 'change_orders' as const

/** Generate a human-readable reference ID: CO-0001 through CO-9999 */
export function generateReferenceId(): string {
  const all = db.list<ChangeOrder>(COLLECTION)
  const maxNum = all.reduce((max, co) => {
    const match = co.reference_id.match(/^CO-(\d+)$/)
    const num = match ? parseInt(match[1]!, 10) : 0
    return Math.max(max, num)
  }, 0)
  return `CO-${String(maxNum + 1).padStart(4, '0')}`
}

/** Get a single change order by ID. */
export function getChangeOrder(id: string): ChangeOrder | undefined {
  return db.getById<ChangeOrder>(COLLECTION, id)
}

/** List all non-archived change orders. */
export function listChangeOrders(): ChangeOrder[] {
  return db.list<ChangeOrder>(COLLECTION)
}

/** List change orders for a specific project. */
export function listChangeOrdersByProject(projectId: string): ChangeOrder[] {
  return db.query<ChangeOrder>(COLLECTION, {
    linked_project_id: projectId,
  } as db.QueryFilter<ChangeOrder>)
}

/** List change orders for a specific mobilization. */
export function listChangeOrdersByMobilization(mobilizationId: string): ChangeOrder[] {
  return db.query<ChangeOrder>(COLLECTION, {
    linked_mobilization_id: mobilizationId,
  } as db.QueryFilter<ChangeOrder>)
}

/** Create a new change order. Generates reference_id and sets initial status. */
export function createChangeOrder(
  data: Omit<ChangeOrder, db.AutoGeneratedKeys | db.DefaultableKeys | 'reference_id' | 'status'>
    & Partial<Pick<ChangeOrder, db.DefaultableKeys & keyof ChangeOrder>>,
  actorId: string,
): ChangeOrder {
  const reference_id = generateReferenceId()
  return db.create<ChangeOrder>(
    COLLECTION,
    {
      ...data,
      reference_id,
      status: 'draft',
    } as Omit<ChangeOrder, db.AutoGeneratedKeys>,
    actorId,
  )
}

/** Update an existing change order. */
export function updateChangeOrder(
  id: string,
  changes: Partial<Omit<ChangeOrder, keyof db.BaseEntity>>,
  actorId: string,
  reason?: string,
): ChangeOrder {
  return db.update<ChangeOrder>(COLLECTION, id, changes, actorId, reason)
}

/** Soft-delete a change order. */
export function archiveChangeOrder(id: string, actorId: string, reason: string): void {
  db.softDelete(COLLECTION, id, actorId, reason)
}

/** Get audit log for a specific change order. */
export function getChangeOrderAuditLog(changeOrderId: string) {
  return db.getAuditLog(COLLECTION, changeOrderId)
}
