/**
 * Closeout Plan Data Access Layer
 */

import * as db from './json-db'
import type { CloseoutPlan } from '@/types/commercial'

const COLLECTION = 'closeout_plans' as const

export function generateReferenceId(): string {
  const all = db.list<CloseoutPlan>(COLLECTION)
  const maxNum = all.reduce((max, c) => {
    const match = c.reference_id.match(/^COP-(\d+)$/)
    const num = match ? parseInt(match[1]!, 10) : 0
    return Math.max(max, num)
  }, 0)
  return `COP-${String(maxNum + 1).padStart(4, '0')}`
}

export function getCloseoutPlan(id: string): CloseoutPlan | undefined {
  return db.getById<CloseoutPlan>(COLLECTION, id)
}

export function listCloseoutPlans(): CloseoutPlan[] {
  return db.list<CloseoutPlan>(COLLECTION)
}

export function listCloseoutPlansByPursuit(pursuitId: string): CloseoutPlan[] {
  return db.query<CloseoutPlan>(COLLECTION, {
    pursuit_id: pursuitId,
  } as db.QueryFilter<CloseoutPlan>)
}

export function createCloseoutPlan(
  data: Omit<CloseoutPlan, db.AutoGeneratedKeys | db.DefaultableKeys | 'reference_id'>
    & Partial<Pick<CloseoutPlan, db.DefaultableKeys & keyof CloseoutPlan>>,
  actorId: string,
): CloseoutPlan {
  const reference_id = generateReferenceId()
  return db.create<CloseoutPlan>(
    COLLECTION,
    {
      ...data,
      reference_id,
    } as Omit<CloseoutPlan, db.AutoGeneratedKeys>,
    actorId,
  )
}

export function updateCloseoutPlan(
  id: string,
  changes: Partial<Omit<CloseoutPlan, keyof db.BaseEntity>>,
  actorId: string,
  reason?: string,
): CloseoutPlan {
  return db.update<CloseoutPlan>(COLLECTION, id, changes, actorId, reason)
}

export function getCloseoutPlanAuditLog(planId: string) {
  return db.getAuditLog(COLLECTION, planId)
}
