/**
 * Contact Data Access Layer
 */

import * as db from './json-db'
import type { Contact } from '@/types/commercial'

const COLLECTION = 'contacts' as const

/** Generate a human-readable reference ID: CON-0001 through CON-9999 */
export function generateReferenceId(): string {
  const all = db.list<Contact>(COLLECTION)
  const maxNum = all.reduce((max, c) => {
    const match = c.reference_id.match(/^CON-(\d+)$/)
    const num = match ? parseInt(match[1]!, 10) : 0
    return Math.max(max, num)
  }, 0)
  return `CON-${String(maxNum + 1).padStart(4, '0')}`
}

/** Get a single contact by ID. */
export function getContact(id: string): Contact | undefined {
  return db.getById<Contact>(COLLECTION, id)
}

/** List all non-deleted contacts. */
export function listContacts(): Contact[] {
  return db.list<Contact>(COLLECTION)
}

/** List contacts for a specific client. */
export function listContactsByClient(clientId: string): Contact[] {
  return db.query<Contact>(COLLECTION, {
    client_id: clientId,
  } as db.QueryFilter<Contact>)
}

/** Create a new contact. Generates reference_id and sets defaults. */
export function createContact(
  data: Omit<Contact, db.AutoGeneratedKeys | 'reference_id' | 'touch_count'> & {
    touch_count?: number
  },
  actorId: string,
): Contact {
  const reference_id = generateReferenceId()
  return db.create<Contact>(
    COLLECTION,
    {
      ...data,
      reference_id,
      touch_count: data.touch_count ?? 0,
    } as Omit<Contact, db.AutoGeneratedKeys>,
    actorId,
  )
}

/** Update an existing contact. */
export function updateContact(
  id: string,
  changes: Partial<Omit<Contact, keyof db.BaseEntity>>,
  actorId: string,
  reason?: string,
): Contact {
  return db.update<Contact>(COLLECTION, id, changes, actorId, reason)
}

/** Soft-delete a contact. */
export function archiveContact(id: string, actorId: string, reason: string): void {
  db.softDelete(COLLECTION, id, actorId, reason)
}

/** Get audit log for a specific contact. */
export function getContactAuditLog(contactId: string) {
  return db.getAuditLog(COLLECTION, contactId)
}
