/**
 * Equipment Template Data Access Layer
 *
 * Reusable equipment checklist templates for mobilizations.
 */

import * as db from './json-db'
import type { EquipmentTemplate } from '@/types/commercial'

const COLLECTION = 'equipment_templates' as const

/** Get a single equipment template by ID. */
export function getEquipmentTemplate(id: string): EquipmentTemplate | undefined {
  return db.getById<EquipmentTemplate>(COLLECTION, id)
}

/** List all non-archived equipment templates. */
export function listEquipmentTemplates(): EquipmentTemplate[] {
  return db.list<EquipmentTemplate>(COLLECTION)
}

/** Create a new equipment template. */
export function createEquipmentTemplate(
  data: {
    name: string
    description: string
    items: EquipmentTemplate['items']
    build_types: string[]
  },
  actorId: string,
): EquipmentTemplate {
  return db.create<EquipmentTemplate>(
    COLLECTION,
    data as Omit<EquipmentTemplate, db.AutoGeneratedKeys>,
    actorId,
  )
}

/** Update an existing equipment template. */
export function updateEquipmentTemplate(
  id: string,
  changes: Partial<Pick<EquipmentTemplate, 'name' | 'description' | 'items' | 'build_types'>>,
  actorId: string,
): EquipmentTemplate {
  return db.update<EquipmentTemplate>(COLLECTION, id, changes, actorId)
}

/** Soft-delete an equipment template. */
export function archiveEquipmentTemplate(id: string, actorId: string, reason: string): void {
  db.softDelete(COLLECTION, id, actorId, reason)
}
