/**
 * Estimate Data Access Layer
 *
 * All estimate reads/writes go through these functions.
 */

import * as db from './json-db'
import type { Estimate } from '@/types/commercial'

const COLLECTION = 'estimates' as const

/** Generate a human-readable reference ID: EST-0001 through EST-9999 */
export function generateReferenceId(): string {
  const all = db.list<Estimate>(COLLECTION)
  const maxNum = all.reduce((max, e) => {
    const match = e.reference_id.match(/^EST-(\d+)$/)
    const num = match ? parseInt(match[1]!, 10) : 0
    return Math.max(max, num)
  }, 0)
  return `EST-${String(maxNum + 1).padStart(4, '0')}`
}

/** Get a single estimate by ID. */
export function getEstimate(id: string): Estimate | undefined {
  return db.getById<Estimate>(COLLECTION, id)
}

/** List all non-archived estimates. */
export function listEstimates(): Estimate[] {
  return db.list<Estimate>(COLLECTION)
}

/** List estimates for a specific pursuit. */
export function listEstimatesByPursuit(pursuitId: string): Estimate[] {
  return db.query<Estimate>(COLLECTION, {
    linked_pursuit_id: pursuitId,
  } as db.QueryFilter<Estimate>)
}

/** List estimates for a specific client. */
export function listEstimatesByClient(clientId: string): Estimate[] {
  return db.query<Estimate>(COLLECTION, {
    linked_client_id: clientId,
  } as db.QueryFilter<Estimate>)
}

/** Get the active (non-superseded) estimate for a pursuit. */
export function getActiveEstimateForPursuit(pursuitId: string): Estimate | undefined {
  const estimates = listEstimatesByPursuit(pursuitId)
  return estimates.find((e) => e.status !== 'superseded')
}

/** Create a new estimate. Generates reference_id and sets initial status. */
export function createEstimate(
  data: Omit<Estimate, db.AutoGeneratedKeys | db.DefaultableKeys | 'reference_id' | 'status' | 'version' | 'superseded_by_id'>
    & Partial<Pick<Estimate, db.DefaultableKeys & keyof Estimate>>
    & { version?: number; superseded_by_id?: string | null },
  actorId: string,
): Estimate {
  const reference_id = generateReferenceId()
  return db.create<Estimate>(
    COLLECTION,
    {
      ...data,
      reference_id,
      status: 'draft',
      version: data.version ?? 1,
      superseded_by_id: data.superseded_by_id ?? null,
    } as Omit<Estimate, db.AutoGeneratedKeys>,
    actorId,
  )
}

/** Update an existing estimate. */
export function updateEstimate(
  id: string,
  changes: Partial<Omit<Estimate, keyof db.BaseEntity>>,
  actorId: string,
  reason?: string,
): Estimate {
  return db.update<Estimate>(COLLECTION, id, changes, actorId, reason)
}

/** Soft-delete an estimate. */
export function archiveEstimate(id: string, actorId: string, reason: string): void {
  db.softDelete(COLLECTION, id, actorId, reason)
}

/** Get audit log for a specific estimate. */
export function getEstimateAuditLog(estimateId: string) {
  return db.getAuditLog(COLLECTION, estimateId)
}
