/**
 * Expansion Task Data Access Layer
 *
 * All expansion task reads/writes go through these functions.
 */

import * as db from './json-db'
import type { ExpansionTask } from '@/types/commercial'

const COLLECTION = 'expansion_tasks' as const

/** Generate a human-readable reference ID: EXP-0001 through EXP-9999 */
export function generateReferenceId(): string {
  const all = db.list<ExpansionTask>(COLLECTION)
  const maxNum = all.reduce((max, et) => {
    const match = et.reference_id.match(/^EXP-(\d+)$/)
    const num = match ? parseInt(match[1]!, 10) : 0
    return Math.max(max, num)
  }, 0)
  return `EXP-${String(maxNum + 1).padStart(4, '0')}`
}

/** Get a single expansion task by ID. */
export function getExpansionTask(id: string): ExpansionTask | undefined {
  return db.getById<ExpansionTask>(COLLECTION, id)
}

/** List all non-archived expansion tasks. */
export function listExpansionTasks(): ExpansionTask[] {
  return db.list<ExpansionTask>(COLLECTION)
}

/** List expansion tasks for a specific project. */
export function listExpansionTasksByProject(projectId: string): ExpansionTask[] {
  return db.query<ExpansionTask>(COLLECTION, {
    linked_project_id: projectId,
  } as db.QueryFilter<ExpansionTask>)
}

/** List expansion tasks for a specific client. */
export function listExpansionTasksByClient(clientId: string): ExpansionTask[] {
  return db.query<ExpansionTask>(COLLECTION, {
    linked_client_id: clientId,
  } as db.QueryFilter<ExpansionTask>)
}

/** Create a new expansion task. Generates reference_id and sets initial status. */
export function createExpansionTask(
  data: Omit<ExpansionTask, db.AutoGeneratedKeys | db.DefaultableKeys | 'reference_id' | 'status'>
    & Partial<Pick<ExpansionTask, db.DefaultableKeys & keyof ExpansionTask>>,
  actorId: string,
): ExpansionTask {
  const reference_id = generateReferenceId()
  return db.create<ExpansionTask>(
    COLLECTION,
    {
      ...data,
      reference_id,
      status: 'open',
    } as Omit<ExpansionTask, db.AutoGeneratedKeys>,
    actorId,
  )
}

/** Update an existing expansion task. */
export function updateExpansionTask(
  id: string,
  changes: Partial<Omit<ExpansionTask, keyof db.BaseEntity>>,
  actorId: string,
  reason?: string,
): ExpansionTask {
  return db.update<ExpansionTask>(COLLECTION, id, changes, actorId, reason)
}

/** Soft-delete an expansion task. */
export function archiveExpansionTask(id: string, actorId: string, reason: string): void {
  db.softDelete(COLLECTION, id, actorId, reason)
}

/** Get audit log for a specific expansion task. */
export function getExpansionTaskAuditLog(expansionTaskId: string) {
  return db.getAuditLog(COLLECTION, expansionTaskId)
}
