import fs from 'fs'
import path from 'path'
import { v4 as uuidv4 } from 'uuid'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type ArchiveState = 'active' | 'archived' | 'reactivated'

/** Keys that are auto-generated by create() and should never be passed by callers. */
export type AutoGeneratedKeys = 'id' | 'created_at' | 'updated_at' | 'created_by' | 'updated_by' | 'archive_state'

export interface BaseEntity {
  id: string
  created_at: string
  updated_at: string
  created_by: string
  updated_by: string
  /** Active / Archived / Reactivated — replaces is_deleted (ERP-12) */
  archive_state: ArchiveState
  /** Current accountable owner user ID (ERP-12 global field) */
  owner: string
  /** Secondary owner where continuity matters (ERP-12 global field) */
  backup_owner: string | null
  /** Human-readable next move (ERP-12 global field) */
  next_action: string | null
  /** Due date for the next move (ISO string) (ERP-12 global field) */
  next_action_date: string | null
  /** Optional controlled secondary indicator (ERP-12 global field) */
  stage_or_substatus: string | null
  /** True when work is moving under an approved exception (ERP-12 global field) */
  exception_flag: boolean
  /** Canonical SharePoint link or file-path reference (ERP-12 global field) */
  file_link: string | null
}

export interface AuditEntry {
  id: string
  timestamp: string
  actor_id: string
  entity_type: string
  entity_id: string
  action: 'create' | 'update' | 'delete' | 'transition'
  field_changes: Record<string, { from: unknown; to: unknown }>
  reason?: string
}

export interface IntegrationEvent {
  id: string
  event_type: string
  source_entity: string
  source_id: string
  payload: Record<string, unknown>
  timestamp: string
  status: 'pending' | 'sent' | 'failed' | 'manual_override'
  target_system: string
  retry_count: number
  failure_reason: string | null
  manual_override_note: string | null
}

export interface DatabaseSchema {
  clients: Record<string, BaseEntity & Record<string, unknown>>
  contacts: Record<string, BaseEntity & Record<string, unknown>>
  project_signals: Record<string, BaseEntity & Record<string, unknown>>
  pursuits: Record<string, BaseEntity & Record<string, unknown>>
  estimates: Record<string, BaseEntity & Record<string, unknown>>
  proposals: Record<string, BaseEntity & Record<string, unknown>>
  award_handoffs: Record<string, BaseEntity & Record<string, unknown>>
  projects: Record<string, BaseEntity & Record<string, unknown>>
  mobilizations: Record<string, BaseEntity & Record<string, unknown>>
  change_orders: Record<string, BaseEntity & Record<string, unknown>>
  expansion_tasks: Record<string, BaseEntity & Record<string, unknown>>
  integration_events: IntegrationEvent[]
  audit_log: AuditEntry[]
}

export type CollectionName = keyof Omit<DatabaseSchema, 'audit_log'>

export type QueryFilter<T> = {
  [K in keyof T]?: T[K] | ((value: T[K]) => boolean)
}

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const DB_DIR = path.join(process.cwd(), '.data')
const DB_PATH = path.join(DB_DIR, 'workflow-db.json')

function emptyDb(): DatabaseSchema {
  return {
    clients: {},
    contacts: {},
    project_signals: {},
    pursuits: {},
    estimates: {},
    proposals: {},
    award_handoffs: {},
    projects: {},
    mobilizations: {},
    change_orders: {},
    expansion_tasks: {},
    integration_events: [],
    audit_log: [],
  }
}

// ---------------------------------------------------------------------------
// Low-level read/write
// ---------------------------------------------------------------------------

function ensureDbExists(): void {
  if (!fs.existsSync(DB_DIR)) {
    fs.mkdirSync(DB_DIR, { recursive: true })
  }
  if (!fs.existsSync(DB_PATH)) {
    fs.writeFileSync(DB_PATH, JSON.stringify(emptyDb(), null, 2), 'utf-8')
  }
}

function readDb(): DatabaseSchema {
  ensureDbExists()
  const raw = fs.readFileSync(DB_PATH, 'utf-8')
  return JSON.parse(raw) as DatabaseSchema
}

function writeDb(data: DatabaseSchema): void {
  ensureDbExists()
  fs.writeFileSync(DB_PATH, JSON.stringify(data, null, 2), 'utf-8')
}

// ---------------------------------------------------------------------------
// Audit helper
// ---------------------------------------------------------------------------

function logAudit(
  db: DatabaseSchema,
  entry: Omit<AuditEntry, 'id' | 'timestamp'>,
): void {
  db.audit_log.push({
    ...entry,
    id: uuidv4(),
    timestamp: new Date().toISOString(),
  })
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Get a single entity by ID. Returns undefined if not found or archived. */
export function getById<T extends BaseEntity>(
  collection: CollectionName,
  id: string,
): T | undefined {
  const db = readDb()
  const entity = db[collection][id] as T | undefined
  if (!entity || entity.archive_state === 'archived') return undefined
  return entity
}

/** List all non-archived entities in a collection. */
export function list<T extends BaseEntity>(
  collection: CollectionName,
): T[] {
  const db = readDb()
  return Object.values(db[collection]).filter(
    (e) => e.archive_state !== 'archived',
  ) as T[]
}

/** Query entities matching filter criteria. */
export function query<T extends BaseEntity>(
  collection: CollectionName,
  filter: QueryFilter<T>,
): T[] {
  const all = list<T>(collection)
  return all.filter((entity) =>
    Object.entries(filter).every(([key, condition]) => {
      const value = (entity as Record<string, unknown>)[key]
      if (typeof condition === 'function') {
        return (condition as (v: unknown) => boolean)(value)
      }
      return value === condition
    }),
  )
}

/** Create a new entity. Returns the created entity with generated ID. */
export function create<T extends BaseEntity>(
  collection: CollectionName,
  data: Omit<T, AutoGeneratedKeys> & { id?: string },
  actorId: string,
): T {
  const db = readDb()
  const now = new Date().toISOString()
  const id = data.id ?? uuidv4()

  const entity = {
    // Defaults for global fields (overridable via data)
    owner: actorId,
    backup_owner: null,
    next_action: null,
    next_action_date: null,
    stage_or_substatus: null,
    exception_flag: false,
    file_link: null,
    // Entity-specific data (may override global defaults above)
    ...data,
    // Auto-generated fields (never overridable)
    id,
    created_at: now,
    updated_at: now,
    created_by: actorId,
    updated_by: actorId,
    archive_state: 'active' as ArchiveState,
  } as unknown as T

  db[collection][id] = entity as BaseEntity & Record<string, unknown>

  logAudit(db, {
    actor_id: actorId,
    entity_type: collection,
    entity_id: id,
    action: 'create',
    field_changes: {},
  })

  writeDb(db)
  return entity
}

/** Update an existing entity. Returns the updated entity. */
export function update<T extends BaseEntity>(
  collection: CollectionName,
  id: string,
  changes: Partial<Omit<T, AutoGeneratedKeys>>,
  actorId: string,
  reason?: string,
): T {
  const db = readDb()
  const existing = db[collection][id]
  if (!existing || existing.archive_state === 'archived') {
    throw new Error(`Entity ${id} not found in ${collection}`)
  }

  const fieldChanges: Record<string, { from: unknown; to: unknown }> = {}
  for (const [key, value] of Object.entries(changes)) {
    const oldVal = (existing as Record<string, unknown>)[key]
    if (oldVal !== value) {
      fieldChanges[key] = { from: oldVal, to: value }
    }
  }

  const updated = {
    ...existing,
    ...changes,
    updated_at: new Date().toISOString(),
    updated_by: actorId,
  }

  db[collection][id] = updated

  logAudit(db, {
    actor_id: actorId,
    entity_type: collection,
    entity_id: id,
    action: 'update',
    field_changes: fieldChanges,
    reason,
  })

  writeDb(db)
  return updated as unknown as T
}

/** Archive an entity (soft-delete). Sets archive_state to 'archived'. */
export function softDelete(
  collection: CollectionName,
  id: string,
  actorId: string,
  reason: string,
): void {
  const db = readDb()
  const existing = db[collection][id]
  if (!existing || existing.archive_state === 'archived') {
    throw new Error(`Entity ${id} not found in ${collection}`)
  }

  const previousState = existing.archive_state
  existing.archive_state = 'archived'
  existing.updated_at = new Date().toISOString()
  existing.updated_by = actorId

  logAudit(db, {
    actor_id: actorId,
    entity_type: collection,
    entity_id: id,
    action: 'delete',
    field_changes: { archive_state: { from: previousState, to: 'archived' } },
    reason,
  })

  writeDb(db)
}

/** Get audit log entries for a specific entity. */
export function getAuditLog(
  entityType: CollectionName,
  entityId: string,
): AuditEntry[] {
  const db = readDb()
  return db.audit_log.filter(
    (e) => e.entity_type === entityType && e.entity_id === entityId,
  )
}

// ---------------------------------------------------------------------------
// Integration Events API
// ---------------------------------------------------------------------------

/** Append an integration event. */
export function addIntegrationEvent(event: IntegrationEvent): void {
  const db = readDb()
  db.integration_events.push(event)
  writeDb(db)
}

/** List all integration events (optionally filtered). */
export function listIntegrationEvents(filter?: {
  status?: IntegrationEvent['status']
  target_system?: string
}): IntegrationEvent[] {
  const db = readDb()
  let events = db.integration_events
  if (filter?.status) {
    events = events.filter((e) => e.status === filter.status)
  }
  if (filter?.target_system) {
    events = events.filter((e) => e.target_system === filter.target_system)
  }
  return events
}

/** Update an integration event by ID. */
export function updateIntegrationEvent(
  eventId: string,
  changes: Partial<IntegrationEvent>,
): IntegrationEvent | undefined {
  const db = readDb()
  const idx = db.integration_events.findIndex((e) => e.id === eventId)
  if (idx === -1) return undefined
  db.integration_events[idx] = { ...db.integration_events[idx]!, ...changes }
  writeDb(db)
  return db.integration_events[idx]
}

/** Reset the database (for testing only). */
export function resetDb(): void {
  writeDb(emptyDb())
}
