/**
 * Mobilization Data Access Layer
 *
 * All mobilization reads/writes go through these functions.
 */

import * as db from './json-db'
import type { Mobilization } from '@/types/commercial'

const COLLECTION = 'mobilizations' as const

/** Generate a human-readable reference ID: MOB-0001 through MOB-9999 */
export function generateReferenceId(): string {
  const all = db.list<Mobilization>(COLLECTION)
  const maxNum = all.reduce((max, m) => {
    const match = m.reference_id.match(/^MOB-(\d+)$/)
    const num = match ? parseInt(match[1]!, 10) : 0
    return Math.max(max, num)
  }, 0)
  return `MOB-${String(maxNum + 1).padStart(4, '0')}`
}

/** Get a single mobilization by ID. */
export function getMobilization(id: string): Mobilization | undefined {
  return db.getById<Mobilization>(COLLECTION, id)
}

/** List all non-archived mobilizations. */
export function listMobilizations(): Mobilization[] {
  return db.list<Mobilization>(COLLECTION)
}

/** List mobilizations for a specific project. */
export function listMobilizationsByProject(projectId: string): Mobilization[] {
  return db.query<Mobilization>(COLLECTION, {
    linked_project_id: projectId,
  } as db.QueryFilter<Mobilization>)
}

/** Create a new mobilization. Generates reference_id and sets initial status. */
export function createMobilization(
  data: Omit<Mobilization, db.AutoGeneratedKeys | 'reference_id' | 'status'>,
  actorId: string,
): Mobilization {
  const reference_id = generateReferenceId()
  return db.create<Mobilization>(
    COLLECTION,
    {
      ...data,
      reference_id,
      status: 'handoff_incomplete',
    } as Omit<Mobilization, db.AutoGeneratedKeys>,
    actorId,
  )
}

/** Update an existing mobilization. */
export function updateMobilization(
  id: string,
  changes: Partial<Omit<Mobilization, keyof db.BaseEntity>>,
  actorId: string,
  reason?: string,
): Mobilization {
  return db.update<Mobilization>(COLLECTION, id, changes, actorId, reason)
}

/** Soft-delete a mobilization. */
export function archiveMobilization(id: string, actorId: string, reason: string): void {
  db.softDelete(COLLECTION, id, actorId, reason)
}

/** Get audit log for a specific mobilization. */
export function getMobilizationAuditLog(mobilizationId: string) {
  return db.getAuditLog(COLLECTION, mobilizationId)
}
