/**
 * Project Signal Data Access Layer
 *
 * All project signal reads/writes go through these functions.
 * Uses the generic JSON DB utility under the hood.
 */

import * as db from './json-db'
import type { ProjectSignal } from '@/types/commercial'

const COLLECTION = 'project_signals' as const

/** Generate a human-readable reference ID: SIG-0001 through SIG-9999 */
export function generateReferenceId(): string {
  const all = db.list<ProjectSignal>(COLLECTION)
  const maxNum = all.reduce((max, s) => {
    const match = s.reference_id.match(/^SIG-(\d+)$/)
    const num = match ? parseInt(match[1]!, 10) : 0
    return Math.max(max, num)
  }, 0)
  return `SIG-${String(maxNum + 1).padStart(4, '0')}`
}

/** Get a single project signal by ID. */
export function getProjectSignal(id: string): ProjectSignal | undefined {
  return db.getById<ProjectSignal>(COLLECTION, id)
}

/** List all non-archived project signals. */
export function listProjectSignals(): ProjectSignal[] {
  return db.list<ProjectSignal>(COLLECTION)
}

/** List project signals for a specific client. */
export function listProjectSignalsByClient(clientId: string): ProjectSignal[] {
  return db.query<ProjectSignal>(COLLECTION, {
    linked_client_id: clientId,
  } as db.QueryFilter<ProjectSignal>)
}

/** Create a new project signal. Generates reference_id and sets initial status. */
export function createProjectSignal(
  data: Omit<ProjectSignal, db.AutoGeneratedKeys | 'reference_id' | 'status' | 'gate_outcome' | 'gate_decision_by' | 'gate_decision_date' | 'created_pursuit_id'>,
  actorId: string,
): ProjectSignal {
  const reference_id = generateReferenceId()
  return db.create<ProjectSignal>(
    COLLECTION,
    {
      ...data,
      reference_id,
      status: 'received',
      gate_outcome: 'pending',
      gate_decision_by: null,
      gate_decision_date: null,
    } as Omit<ProjectSignal, db.AutoGeneratedKeys>,
    actorId,
  )
}

/** Update an existing project signal. */
export function updateProjectSignal(
  id: string,
  changes: Partial<Omit<ProjectSignal, keyof db.BaseEntity>>,
  actorId: string,
  reason?: string,
): ProjectSignal {
  return db.update<ProjectSignal>(COLLECTION, id, changes, actorId, reason)
}

/** Soft-delete a project signal. */
export function archiveProjectSignal(id: string, actorId: string, reason: string): void {
  db.softDelete(COLLECTION, id, actorId, reason)
}

/** Get audit log for a specific project signal. */
export function getProjectSignalAuditLog(signalId: string) {
  return db.getAuditLog(COLLECTION, signalId)
}
