/**
 * Project Data Access Layer
 *
 * All project reads/writes go through these functions.
 */

import * as db from './json-db'
import type { Project } from '@/types/commercial'

const COLLECTION = 'projects' as const

/** Generate a human-readable reference ID: PRJ-0001 through PRJ-9999 */
export function generateReferenceId(): string {
  const all = db.list<Project>(COLLECTION)
  const maxNum = all.reduce((max, p) => {
    const match = p.reference_id.match(/^PRJ-(\d+)$/)
    const num = match ? parseInt(match[1]!, 10) : 0
    return Math.max(max, num)
  }, 0)
  return `PRJ-${String(maxNum + 1).padStart(4, '0')}`
}

/** Get a single project by ID. */
export function getProject(id: string): Project | undefined {
  return db.getById<Project>(COLLECTION, id)
}

/** List all non-archived projects. */
export function listProjects(): Project[] {
  return db.list<Project>(COLLECTION)
}

/** List projects for a specific client. */
export function listProjectsByClient(clientId: string): Project[] {
  return db.query<Project>(COLLECTION, {
    linked_client_id: clientId,
  } as db.QueryFilter<Project>)
}

/** List projects for a specific award/handoff. */
export function listProjectsByAwardHandoff(awardHandoffId: string): Project[] {
  return db.query<Project>(COLLECTION, {
    linked_award_handoff_id: awardHandoffId,
  } as db.QueryFilter<Project>)
}

/** Create a new project. Generates reference_id and sets initial status. */
export function createProject(
  data: Omit<Project, db.AutoGeneratedKeys | db.DefaultableKeys | 'reference_id' | 'status'>
    & Partial<Pick<Project, db.DefaultableKeys & keyof Project>>,
  actorId: string,
): Project {
  const reference_id = generateReferenceId()
  return db.create<Project>(
    COLLECTION,
    {
      ...data,
      reference_id,
      status: 'startup_pending',
    } as Omit<Project, db.AutoGeneratedKeys>,
    actorId,
  )
}

/** Update an existing project. */
export function updateProject(
  id: string,
  changes: Partial<Omit<Project, keyof db.BaseEntity>>,
  actorId: string,
  reason?: string,
): Project {
  return db.update<Project>(COLLECTION, id, changes, actorId, reason)
}

/** Soft-delete a project. */
export function archiveProject(id: string, actorId: string, reason: string): void {
  db.softDelete(COLLECTION, id, actorId, reason)
}

/** Get audit log for a specific project. */
export function getProjectAuditLog(projectId: string) {
  return db.getAuditLog(COLLECTION, projectId)
}
