/**
 * Proposal Data Access Layer
 *
 * All proposal reads/writes go through these functions.
 */

import * as db from './json-db'
import type { Proposal } from '@/types/commercial'

const COLLECTION = 'proposals' as const

/** Generate a human-readable reference ID: PRO-0001 through PRO-9999 */
export function generateReferenceId(): string {
  const all = db.list<Proposal>(COLLECTION)
  const maxNum = all.reduce((max, p) => {
    const match = p.reference_id.match(/^PRO-(\d+)$/)
    const num = match ? parseInt(match[1]!, 10) : 0
    return Math.max(max, num)
  }, 0)
  return `PRO-${String(maxNum + 1).padStart(4, '0')}`
}

/** Get a single proposal by ID. */
export function getProposal(id: string): Proposal | undefined {
  return db.getById<Proposal>(COLLECTION, id)
}

/** List all non-archived proposals. */
export function listProposals(): Proposal[] {
  return db.list<Proposal>(COLLECTION)
}

/** List proposals for a specific estimate. */
export function listProposalsByEstimate(estimateId: string): Proposal[] {
  return db.query<Proposal>(COLLECTION, {
    linked_estimate_id: estimateId,
  } as db.QueryFilter<Proposal>)
}

/** List proposals for a specific client. */
export function listProposalsByClient(clientId: string): Proposal[] {
  return db.query<Proposal>(COLLECTION, {
    linked_client_id: clientId,
  } as db.QueryFilter<Proposal>)
}

/** Create a new proposal. Generates reference_id and sets initial status. */
export function createProposal(
  data: Omit<Proposal, db.AutoGeneratedKeys | db.DefaultableKeys | 'reference_id' | 'status' | 'created_award_id'>
    & Partial<Pick<Proposal, db.DefaultableKeys & keyof Proposal>>
    & { created_award_id?: string | null },
  actorId: string,
): Proposal {
  const reference_id = generateReferenceId()
  return db.create<Proposal>(
    COLLECTION,
    {
      ...data,
      reference_id,
      status: 'delivered',
      created_award_id: data.created_award_id ?? null,
    } as Omit<Proposal, db.AutoGeneratedKeys>,
    actorId,
  )
}

/** Update an existing proposal. */
export function updateProposal(
  id: string,
  changes: Partial<Omit<Proposal, keyof db.BaseEntity>>,
  actorId: string,
  reason?: string,
): Proposal {
  return db.update<Proposal>(COLLECTION, id, changes, actorId, reason)
}

/** Soft-delete a proposal. */
export function archiveProposal(id: string, actorId: string, reason: string): void {
  db.softDelete(COLLECTION, id, actorId, reason)
}

/** Get audit log for a specific proposal. */
export function getProposalAuditLog(proposalId: string) {
  return db.getAuditLog(COLLECTION, proposalId)
}
