/**
 * Site Walk Event Data Access Layer
 */

import * as db from './json-db'
import type { SiteWalkEvent } from '@/types/commercial'

const COLLECTION = 'site_walks' as const

export function generateReferenceId(): string {
  const all = db.list<SiteWalkEvent>(COLLECTION)
  const maxNum = all.reduce((max, s) => {
    const match = s.reference_id.match(/^SWE-(\d+)$/)
    const num = match ? parseInt(match[1]!, 10) : 0
    return Math.max(max, num)
  }, 0)
  return `SWE-${String(maxNum + 1).padStart(4, '0')}`
}

export function getSiteWalk(id: string): SiteWalkEvent | undefined {
  return db.getById<SiteWalkEvent>(COLLECTION, id)
}

export function listSiteWalks(): SiteWalkEvent[] {
  return db.list<SiteWalkEvent>(COLLECTION)
}

export function listSiteWalksByPursuit(pursuitId: string): SiteWalkEvent[] {
  return db.query<SiteWalkEvent>(COLLECTION, {
    pursuit_id: pursuitId,
  } as db.QueryFilter<SiteWalkEvent>)
}

export function createSiteWalk(
  data: Omit<SiteWalkEvent, db.AutoGeneratedKeys | db.DefaultableKeys | 'reference_id'>
    & Partial<Pick<SiteWalkEvent, db.DefaultableKeys & keyof SiteWalkEvent>>,
  actorId: string,
): SiteWalkEvent {
  const reference_id = generateReferenceId()
  return db.create<SiteWalkEvent>(
    COLLECTION,
    {
      ...data,
      reference_id,
    } as Omit<SiteWalkEvent, db.AutoGeneratedKeys>,
    actorId,
  )
}

export function updateSiteWalk(
  id: string,
  changes: Partial<Omit<SiteWalkEvent, keyof db.BaseEntity>>,
  actorId: string,
  reason?: string,
): SiteWalkEvent {
  return db.update<SiteWalkEvent>(COLLECTION, id, changes, actorId, reason)
}

export function getSiteWalkAuditLog(siteWalkId: string) {
  return db.getAuditLog(COLLECTION, siteWalkId)
}
