/**
 * Pursuit State Machine
 *
 * Pure logic — no database dependency.
 * ERP-13 Table 10: Pursuit stage pipeline.
 *
 * 12 stages:
 *   Project Signal Received → Qualification Underway → Qualified Pursuit →
 *   Preconstruction Packet Open → Site Walk Scheduled → Site Walk Complete →
 *   Pursue/No-Bid Review → BLU Closeout Plan Sent → Estimate Ready →
 *   Hold → Dormant → No Bid
 */

import type { StateMachineDef } from './engine'

// ---------------------------------------------------------------------------
// Pursuit Stages (ERP-13 Table 10)
// ---------------------------------------------------------------------------

export const PURSUIT_STAGES = [
  'project_signal_received',
  'qualification_underway',
  'qualified_pursuit',
  'preconstruction_packet_open',
  'site_walk_scheduled',
  'site_walk_complete',
  'pursue_no_bid_review',
  'blu_closeout_plan_sent',
  'estimate_ready',
  'hold',
  'dormant',
  'no_bid',
] as const

export type PursuitStage = (typeof PURSUIT_STAGES)[number]

export const PURSUIT_STAGE_LABELS: Record<PursuitStage, string> = {
  project_signal_received: 'Project Signal Received',
  qualification_underway: 'Qualification Underway',
  qualified_pursuit: 'Qualified Pursuit',
  preconstruction_packet_open: 'Preconstruction Packet Open',
  site_walk_scheduled: 'Site Walk Scheduled',
  site_walk_complete: 'Site Walk Complete',
  pursue_no_bid_review: 'Pursue / No-Bid Review',
  blu_closeout_plan_sent: 'BLU Closeout Plan Sent',
  estimate_ready: 'Estimate Ready',
  hold: 'Hold',
  dormant: 'Dormant',
  no_bid: 'No Bid',
}

/** Active forward stages (excluding hold, dormant, no_bid) for stage progression tracker */
export const PURSUIT_ACTIVE_STAGES: PursuitStage[] = [
  'project_signal_received',
  'qualification_underway',
  'qualified_pursuit',
  'preconstruction_packet_open',
  'site_walk_scheduled',
  'site_walk_complete',
  'pursue_no_bid_review',
  'blu_closeout_plan_sent',
  'estimate_ready',
]

// ---------------------------------------------------------------------------
// Machine Definition (ERP-13 Table 10)
// ---------------------------------------------------------------------------

export const pursuitStateMachine: StateMachineDef<PursuitStage> = {
  entityType: 'pursuit',
  states: PURSUIT_STAGES,
  initialState: 'project_signal_received',
  terminalStates: ['no_bid'],
  transitions: [
    // --- From Project Signal Received ---
    {
      fromStates: ['project_signal_received'],
      toState: 'qualification_underway',
      requiredFields: ['client_id', 'project_name'],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_bd_qualification_started'],
      blockers: [],
      requiresApproval: false,
      requiresReason: false,
      label: 'Begin Qualification',
    },

    // --- From Qualification Underway ---
    {
      fromStates: ['qualification_underway'],
      toState: 'qualified_pursuit',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_pursuit_qualified'],
      blockers: [],
      requiresApproval: false,
      requiresReason: false,
      label: 'Mark as Qualified',
    },
    {
      fromStates: ['qualification_underway'],
      toState: 'hold',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['log_hold'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'Place on Hold',
    },
    {
      fromStates: ['qualification_underway'],
      toState: 'dormant',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['log_dormant'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'Mark Dormant',
    },
    {
      fromStates: ['qualification_underway'],
      toState: 'no_bid',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['log_no_bid'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'No-Bid',
    },

    // --- From Qualified Pursuit ---
    {
      fromStates: ['qualified_pursuit'],
      toState: 'preconstruction_packet_open',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_packet_opened'],
      blockers: [],
      requiresApproval: false,
      requiresReason: false,
      label: 'Open Preconstruction Packet',
    },
    {
      fromStates: ['qualified_pursuit'],
      toState: 'hold',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['log_hold'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'Place on Hold',
    },
    {
      fromStates: ['qualified_pursuit'],
      toState: 'dormant',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['log_dormant'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'Mark Dormant',
    },
    {
      fromStates: ['qualified_pursuit'],
      toState: 'no_bid',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['log_no_bid'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'No-Bid',
    },

    // --- From Preconstruction Packet Open ---
    {
      fromStates: ['preconstruction_packet_open'],
      toState: 'site_walk_scheduled',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_site_walk_scheduled'],
      blockers: [],
      requiresApproval: false,
      requiresReason: false,
      label: 'Schedule Site Walk',
    },
    {
      fromStates: ['preconstruction_packet_open'],
      toState: 'estimate_ready',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_estimate_ready'],
      blockers: [],
      requiresApproval: false,
      requiresReason: false,
      label: 'Mark Estimate Ready (skip walk)',
    },
    {
      fromStates: ['preconstruction_packet_open'],
      toState: 'hold',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['log_hold'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'Place on Hold',
    },

    // --- From Site Walk Scheduled ---
    {
      fromStates: ['site_walk_scheduled'],
      toState: 'site_walk_complete',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_site_walk_completed'],
      blockers: [],
      requiresApproval: false,
      requiresReason: false,
      label: 'Mark Site Walk Complete',
    },
    {
      fromStates: ['site_walk_scheduled'],
      toState: 'hold',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['log_hold'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'Place on Hold',
    },

    // --- From Site Walk Complete ---
    {
      fromStates: ['site_walk_complete'],
      toState: 'pursue_no_bid_review',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_review_started'],
      blockers: [],
      requiresApproval: false,
      requiresReason: false,
      label: 'Start Pursue/No-Bid Review',
    },
    {
      fromStates: ['site_walk_complete'],
      toState: 'estimate_ready',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_estimate_ready'],
      blockers: [],
      requiresApproval: false,
      requiresReason: false,
      label: 'Mark Estimate Ready',
    },
    {
      fromStates: ['site_walk_complete'],
      toState: 'hold',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['log_hold'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'Place on Hold',
    },

    // --- From Pursue / No-Bid Review ---
    {
      fromStates: ['pursue_no_bid_review'],
      toState: 'blu_closeout_plan_sent',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_closeout_plan_sent'],
      blockers: [],
      requiresApproval: false,
      requiresReason: false,
      label: 'Send BLU Closeout Plan',
    },
    {
      fromStates: ['pursue_no_bid_review'],
      toState: 'estimate_ready',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_estimate_ready'],
      blockers: [],
      requiresApproval: false,
      requiresReason: false,
      label: 'Mark Estimate Ready',
    },
    {
      fromStates: ['pursue_no_bid_review'],
      toState: 'no_bid',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['log_no_bid'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'No-Bid',
    },
    {
      fromStates: ['pursue_no_bid_review'],
      toState: 'hold',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['log_hold'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'Place on Hold',
    },

    // --- From BLU Closeout Plan Sent ---
    {
      fromStates: ['blu_closeout_plan_sent'],
      toState: 'estimate_ready',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_estimate_ready'],
      blockers: [],
      requiresApproval: false,
      requiresReason: false,
      label: 'Mark Estimate Ready',
    },
    {
      fromStates: ['blu_closeout_plan_sent'],
      toState: 'hold',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['log_hold'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'Place on Hold',
    },

    // --- From Hold (can return to prior active stage, dormant, or no-bid) ---
    {
      fromStates: ['hold'],
      toState: 'qualification_underway',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_hold_released'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'Resume to Qualification',
    },
    {
      fromStates: ['hold'],
      toState: 'qualified_pursuit',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_hold_released'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'Resume to Qualified Pursuit',
    },
    {
      fromStates: ['hold'],
      toState: 'preconstruction_packet_open',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_hold_released'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'Resume to Packet Open',
    },
    {
      fromStates: ['hold'],
      toState: 'site_walk_scheduled',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_hold_released'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'Resume to Site Walk Scheduled',
    },
    {
      fromStates: ['hold'],
      toState: 'site_walk_complete',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_hold_released'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'Resume to Site Walk Complete',
    },
    {
      fromStates: ['hold'],
      toState: 'pursue_no_bid_review',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_hold_released'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'Resume to Review',
    },
    {
      fromStates: ['hold'],
      toState: 'blu_closeout_plan_sent',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_hold_released'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'Resume to Closeout Plan Sent',
    },
    {
      fromStates: ['hold'],
      toState: 'dormant',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['log_dormant'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'Mark Dormant',
    },
    {
      fromStates: ['hold'],
      toState: 'no_bid',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['log_no_bid'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'No-Bid',
    },

    // --- From Dormant ---
    {
      fromStates: ['dormant'],
      toState: 'qualification_underway',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['notify_reactivation'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'Reactivate to Qualification',
    },
    {
      fromStates: ['dormant'],
      toState: 'no_bid',
      requiredFields: [],
      requiredRoles: ['leadership_system_admin', 'commercial_bd'],
      sideEffects: ['log_no_bid'],
      blockers: [],
      requiresApproval: false,
      requiresReason: true,
      label: 'No-Bid from Dormant',
    },
  ],
}
