/**
 * NFR Audit Tests (ERP-20)
 * Verify audit logging, soft-delete, and override tracking.
 */
import { describe, it, expect, beforeEach } from 'vitest'
import * as db from '@/lib/db/json-db'

describe('NFR — Audit Trail', () => {
  beforeEach(() => { db.resetDb() })

  it('every entity type logs audit entry on create', () => {
    const collections: db.CollectionName[] = [
      'clients', 'contacts', 'project_signals', 'pursuits', 'estimates',
      'proposals', 'award_handoffs', 'projects', 'mobilizations',
      'change_orders', 'expansion_tasks',
    ]
    for (const col of collections) {
      const entity = db.create(col, {
        reference_id: `TEST-0001`, status: 'test', owner: 'tester',
      } as Omit<db.BaseEntity, db.AutoGeneratedKeys> & Record<string, unknown>, 'test-actor')

      const audit = db.getAuditLog(col, entity.id)
      expect(audit.length).toBeGreaterThanOrEqual(1)
      expect(audit[0]!.action).toBe('create')
      expect(audit[0]!.actor_id).toBe('test-actor')
    }
  })

  it('state transition logs audit entry with field changes', () => {
    const entity = db.create('pursuits', {
      reference_id: 'PUR-0001', linked_signal_id: 'sig-1',
      project_name: 'Test', client_id: 'c1', client_name: 'Test',
      stage: 'project_signal_received', owner: 'tester',
    } as Omit<db.BaseEntity, db.AutoGeneratedKeys> & Record<string, unknown>, 'actor')

    db.update('pursuits', entity.id, { stage: 'qualification_underway' }, 'actor', 'Advanced pursuit')

    const audit = db.getAuditLog('pursuits', entity.id)
    const updateEntry = audit.find(e => e.action === 'update')
    expect(updateEntry).toBeDefined()
    expect(updateEntry!.field_changes['stage']).toEqual({
      from: 'project_signal_received', to: 'qualification_underway',
    })
    expect(updateEntry!.reason).toBe('Advanced pursuit')
  })

  it('manual overrides log approver, reason, date, and evidence', () => {
    const entity = db.create('mobilizations', {
      reference_id: 'MOB-0001', status: 'needs_planning', owner: 'cullen',
      compressed_planning: false, exception_flag: false,
    } as Omit<db.BaseEntity, db.AutoGeneratedKeys> & Record<string, unknown>, 'system')

    db.update('mobilizations', entity.id, {
      compressed_planning: true, exception_flag: true,
    }, 'antonio-leadership', 'Compressed planning override: tight schedule requires exception')

    const audit = db.getAuditLog('mobilizations', entity.id)
    const overrideEntry = audit.find(e => e.reason?.includes('override'))
    expect(overrideEntry).toBeDefined()
    expect(overrideEntry!.actor_id).toBe('antonio-leadership')
    expect(overrideEntry!.field_changes['exception_flag']).toEqual({ from: false, to: true })
  })

  it('soft-delete sets archive_state to archived, never hard-deletes', () => {
    const entity = db.create('clients', {
      reference_id: 'CLT-0001', name: 'Test Co', status: 'watchlist', owner: 'tester',
      preferred_provider_candidate: false, contacts: [],
    } as Omit<db.BaseEntity, db.AutoGeneratedKeys> & Record<string, unknown>, 'actor')

    db.softDelete('clients', entity.id, 'admin', 'No longer relevant')

    // Entity should be archived, not deleted
    const archived = db.getById('clients', entity.id)
    expect(archived).toBeUndefined() // getById filters archived

    // But audit log should show the delete
    const audit = db.getAuditLog('clients', entity.id)
    const deleteEntry = audit.find(e => e.action === 'delete')
    expect(deleteEntry).toBeDefined()
    expect(deleteEntry!.reason).toBe('No longer relevant')
    expect(deleteEntry!.field_changes['archive_state']).toEqual({ from: 'active', to: 'archived' })
  })

  it('archived entities are excluded from list() queries', () => {
    db.create('clients', {
      reference_id: 'CLT-0001', name: 'Active Co', status: 'watchlist', owner: 'tester',
      preferred_provider_candidate: false, contacts: [],
    } as Omit<db.BaseEntity, db.AutoGeneratedKeys> & Record<string, unknown>, 'actor')

    const toArchive = db.create('clients', {
      reference_id: 'CLT-0002', name: 'Archive Co', status: 'watchlist', owner: 'tester',
      preferred_provider_candidate: false, contacts: [],
    } as Omit<db.BaseEntity, db.AutoGeneratedKeys> & Record<string, unknown>, 'actor')

    db.softDelete('clients', toArchive.id, 'admin', 'Archived')

    const all = db.list('clients')
    expect(all.length).toBe(1)
    expect(all[0]!.id).not.toBe(toArchive.id)
  })
})
