/**
 * UAT Scenario 2 — Compressed planning mobilization
 */
import { describe, it, expect, beforeEach } from 'vitest'
import * as db from '@/lib/db/json-db'
import { validateTransition } from '@/lib/state-machines/engine'
import { mobilizationStateMachine } from '@/lib/state-machines/mobilization'
import type { Role } from '@/lib/permissions/roles'

const PM: Role[] = ['leadership_system_admin', 'pm_ops']

describe('UAT Scenario 2 — Compressed Planning', () => {
  beforeEach(() => { db.resetDb() })

  it('allows ready with incomplete checklist when compressed_planning + exception_flag', () => {
    const entity = {
      readiness_checklist: { crew_confirmed: true, equipment_loaded: false, travel_booked: false, lodging_booked: false, per_diem_approved: false, jobber_synced: false, teams_posted: false },
      compressed_planning: true, exception_flag: true, missing_items_log: null,
    }
    const result = validateTransition(mobilizationStateMachine, {
      currentState: 'needs_planning', targetState: 'ready', entity, actorRoles: PM,
    })
    expect(result.allowed).toBe(true)
  })

  it('blocks ready with incomplete checklist without exception_flag', () => {
    const entity = {
      readiness_checklist: { crew_confirmed: true, equipment_loaded: false, travel_booked: false, lodging_booked: false, per_diem_approved: false, jobber_synced: false, teams_posted: false },
      compressed_planning: true, exception_flag: false, missing_items_log: null,
    }
    const result = validateTransition(mobilizationStateMachine, {
      currentState: 'needs_planning', targetState: 'ready', entity, actorRoles: PM,
    })
    expect(result.allowed).toBe(false)
  })

  it('logs exception in audit trail when compressed planning override is used', () => {
    const project = db.create('projects', {
      reference_id: 'PRJ-0001', status: 'execution_active',
      linked_award_handoff_id: 'awd-1', linked_client_id: 'cli-1',
      project_name: 'Test', pm_owner_id: 'cullen',
      commercial_baseline_snapshot: {}, client_stage_map: null,
      target_turnover_date: null, billing_references: null,
      active_change_order_count: 0, owner: 'cullen',
    } as Omit<db.BaseEntity, db.AutoGeneratedKeys | db.DefaultableKeys> & Record<string, unknown>, 'system')

    const mob = db.create('mobilizations', {
      reference_id: 'MOB-0001', status: 'needs_planning',
      linked_project_id: project.id, linked_client_id: 'cli-1',
      stage_name: 'Trip 1', compressed_planning: false, exception_flag: false,
      readiness_checklist: { crew_confirmed: false, equipment_loaded: false, travel_booked: false, lodging_booked: false, per_diem_approved: false, jobber_synced: false, teams_posted: false },
      owner: 'cullen',
    } as Omit<db.BaseEntity, db.AutoGeneratedKeys | db.DefaultableKeys> & Record<string, unknown>, 'system')

    // Apply compressed planning override
    db.update('mobilizations', mob.id, { compressed_planning: true, exception_flag: true }, 'leadership', 'Compressed planning override: tight schedule')

    const audit = db.getAuditLog('mobilizations', mob.id)
    const overrideEntry = audit.find(e => e.reason?.includes('Compressed planning'))
    expect(overrideEntry).toBeDefined()
  })
})
