/**
 * UAT Scenario 6 — Callback / return visit
 */
import { describe, it, expect, beforeEach } from 'vitest'
import * as db from '@/lib/db/json-db'

describe('UAT Scenario 6 — Callback / Return Visit', () => {
  beforeEach(() => { db.resetDb() })

  it('creates a NEW mobilization for return visit (not reusing old record)', () => {
    const project = db.create('projects', {
      reference_id: 'PRJ-0001', status: 'execution_active',
      linked_award_handoff_id: 'awd-1', linked_client_id: 'cli-1',
      project_name: 'Test', pm_owner_id: 'cullen',
      commercial_baseline_snapshot: {}, client_stage_map: null,
      target_turnover_date: null, billing_references: null,
      active_change_order_count: 0, owner: 'cullen',
    } as Omit<db.BaseEntity, db.AutoGeneratedKeys | db.DefaultableKeys> & Record<string, unknown>, 'system')

    // Original completed mobilization
    const mob1 = db.create('mobilizations', {
      reference_id: 'MOB-0001', status: 'complete',
      linked_project_id: project.id, linked_client_id: 'cli-1',
      stage_name: 'Trip 1 — Final Clean', owner: 'cullen',
      readiness_checklist: { crew_confirmed: true, equipment_loaded: true, travel_booked: true, lodging_booked: true, per_diem_approved: true, jobber_synced: true, teams_posted: true },
    } as Omit<db.BaseEntity, db.AutoGeneratedKeys | db.DefaultableKeys> & Record<string, unknown>, 'system')

    // New callback mobilization (separate record)
    const mob2 = db.create('mobilizations', {
      reference_id: 'MOB-0002', status: 'handoff_incomplete',
      linked_project_id: project.id, linked_client_id: 'cli-1',
      stage_name: 'Callback — Punch List Return', owner: 'cullen',
      readiness_checklist: { crew_confirmed: false, equipment_loaded: false, travel_booked: false, lodging_booked: false, per_diem_approved: false, jobber_synced: false, teams_posted: false },
    } as Omit<db.BaseEntity, db.AutoGeneratedKeys | db.DefaultableKeys> & Record<string, unknown>, 'system')

    // Both exist under same project with distinct ref IDs
    const allMobs = db.list('mobilizations') as (db.BaseEntity & Record<string, unknown>)[]
    const projectMobs = allMobs.filter(m => m['linked_project_id'] === project.id)
    expect(projectMobs.length).toBe(2)
    expect(projectMobs[0]!['reference_id']).not.toBe(projectMobs[1]!['reference_id'])

    // Original is still complete (not mutated)
    const original = db.getById('mobilizations', mob1.id) as Record<string, unknown>
    expect(original['status']).toBe('complete')
  })
})
