/**
 * UAT Scenario 4 — Change Order mid-mobilization
 */
import { describe, it, expect, beforeEach } from 'vitest'
import * as db from '@/lib/db/json-db'
import { validateTransition } from '@/lib/state-machines/engine'
import { changeOrderStateMachine } from '@/lib/state-machines/change-order'
import type { ChangeOrder, Project } from '@/types/commercial'
import type { Role } from '@/lib/permissions/roles'

const PM: Role[] = ['pm_ops']
const BD: Role[] = ['commercial_bd']
const EST: Role[] = ['estimating']
const LEAD: Role[] = ['leadership_system_admin']
const FIN: Role[] = ['admin_finance']

describe('UAT Scenario 4 — Change Order Mid-Mobilization', () => {
  beforeEach(() => { db.resetDb() })

  it('full CO lifecycle with pricing control and baseline preservation', () => {
    // Setup project
    const project = db.create<Project>('projects', {
      reference_id: 'PRJ-0001', status: 'execution_active',
      linked_award_handoff_id: 'awd-1', linked_client_id: 'cli-1',
      project_name: 'Test', pm_owner_id: 'cullen',
      commercial_baseline_snapshot: { proposal_value: 25000 },
      client_stage_map: null, target_turnover_date: null, billing_references: null,
      active_change_order_count: 0, owner: 'cullen',
    } as Omit<Project, db.AutoGeneratedKeys>, 'system')

    // Create CO
    const co = db.create<ChangeOrder>('change_orders', {
      reference_id: 'CO-0001', status: 'draft',
      linked_project_id: project.id, linked_mobilization_id: 'mob-1',
      linked_client_id: 'cli-1', origin: 'pm_field_discovery',
      scope_delta: 'Added window cleaning', pricing_delta: null,
      schedule_delta: null, mobilization_impact: null,
      fact_packet_by: 'cullen', priced_by: null,
      approval_notes: null, release_notes: null,
      client_response_date: null, rejection_reason: null, owner: 'cullen',
    } as Omit<ChangeOrder, db.AutoGeneratedKeys>, 'system')

    const entity = { ...co } as Record<string, unknown>

    // draft → internal_review (PM submits)
    let result = validateTransition(changeOrderStateMachine, {
      currentState: 'draft', targetState: 'internal_review', entity, actorRoles: PM,
    })
    expect(result.allowed).toBe(true)
    entity['status'] = 'internal_review'

    // PM cannot send to client (wrong role for pricing)
    result = validateTransition(changeOrderStateMachine, {
      currentState: 'internal_review', targetState: 'client_pending', entity, actorRoles: PM,
    })
    expect(result.allowed).toBe(false)

    // Add pricing (by estimating)
    entity['pricing_delta'] = { original_value: 25000, revised_value: 27500, delta: 2500 }
    entity['priced_by'] = 'antonio'

    // PM who documented facts cannot also price
    const selfPriceEntity = { ...entity, priced_by: 'cullen' }
    result = validateTransition(changeOrderStateMachine, {
      currentState: 'internal_review', targetState: 'client_pending', entity: selfPriceEntity, actorRoles: LEAD,
    })
    expect(result.allowed).toBe(false)
    expect(result.errors.some(e => e.includes('cannot also price'))).toBe(true)

    // Estimating sends to client
    result = validateTransition(changeOrderStateMachine, {
      currentState: 'internal_review', targetState: 'client_pending', entity, actorRoles: EST,
    })
    expect(result.allowed).toBe(true)
    entity['status'] = 'client_pending'

    // client_pending → approved
    entity['client_response_date'] = '2026-04-01'
    result = validateTransition(changeOrderStateMachine, {
      currentState: 'client_pending', targetState: 'approved', entity, actorRoles: BD,
    })
    expect(result.allowed).toBe(true)
    entity['status'] = 'approved'

    // approved → released
    result = validateTransition(changeOrderStateMachine, {
      currentState: 'approved', targetState: 'released', entity, actorRoles: PM,
    })
    expect(result.allowed).toBe(true)
    entity['status'] = 'released'

    // released → closed (only admin_finance or leadership)
    result = validateTransition(changeOrderStateMachine, {
      currentState: 'released', targetState: 'closed', entity, actorRoles: PM,
    })
    expect(result.allowed).toBe(false)
    result = validateTransition(changeOrderStateMachine, {
      currentState: 'released', targetState: 'closed', entity, actorRoles: FIN,
    })
    expect(result.allowed).toBe(true)

    // Verify baseline preserved
    const updatedProject = db.getById<Project>('projects', project.id)!
    expect((updatedProject.commercial_baseline_snapshot as Record<string, unknown>)['proposal_value']).toBe(25000)
  })
})
