/**
 * UAT Scenario 8 — Full lifecycle: closeout to AR to expansion to new signal
 */
import { describe, it, expect, beforeEach } from 'vitest'
import * as db from '@/lib/db/json-db'
import { validateTransition } from '@/lib/state-machines/engine'
import { projectStateMachine } from '@/lib/state-machines/project'
import { expansionTaskStateMachine } from '@/lib/state-machines/expansion-task'
import { autoCreateExpansionTaskAction } from '@/actions/expansion-task'
import type { Project, ExpansionTask, ProjectSignal } from '@/types/commercial'
import type { Role } from '@/lib/permissions/roles'

const PM: Role[] = ['leadership_system_admin', 'pm_ops']
const BD: Role[] = ['leadership_system_admin', 'commercial_bd']
const FIN: Role[] = ['leadership_system_admin', 'admin_finance']

describe('UAT Scenario 8 — Full Lifecycle with Expansion Loop', () => {
  beforeEach(() => { db.resetDb() })

  it('project closeout → expansion task → new signal → full circle', async () => {
    // Create project at operationally_complete
    const project = db.create<Project>('projects', {
      reference_id: 'PRJ-0001', status: 'operationally_complete',
      linked_award_handoff_id: 'awd-1', linked_client_id: 'cli-1',
      project_name: 'Crunch Fitness', pm_owner_id: 'cullen',
      commercial_baseline_snapshot: { proposal_value: 25000 },
      client_stage_map: null, target_turnover_date: null, billing_references: null,
      active_change_order_count: 0, owner: 'cullen',
    } as Omit<Project, db.AutoGeneratedKeys>, 'system')

    // Auto-create expansion task
    const result = await autoCreateExpansionTaskAction(project.id)
    expect(result.success).toBe(true)
    expect(result.data?.task_type).toBe('thank_you')
    const expTask = result.data!

    // Advance project: operationally_complete → financially_open → financially_closed
    let projEntity = { ...project, mobilization_count: 1, open_mobilization_count: 0 } as Record<string, unknown>
    let tr = validateTransition(projectStateMachine, {
      currentState: 'operationally_complete', targetState: 'financially_open',
      entity: projEntity, actorRoles: FIN,
    })
    expect(tr.allowed).toBe(true)
    projEntity['status'] = 'financially_open'
    tr = validateTransition(projectStateMachine, {
      currentState: 'financially_open', targetState: 'financially_closed',
      entity: projEntity, actorRoles: FIN,
    })
    expect(tr.allowed).toBe(true)

    // Advance expansion task: open → in_progress → complete
    const etEntity = { ...expTask, owner: 'marcus-johnson', due_date: '2026-04-10', next_action_date: '2026-04-05' } as Record<string, unknown>
    tr = validateTransition(expansionTaskStateMachine, {
      currentState: 'open', targetState: 'in_progress',
      entity: etEntity, actorRoles: BD,
    })
    expect(tr.allowed).toBe(true)
    etEntity['status'] = 'in_progress'

    // Create new Project Signal from expansion (the growth loop)
    const newSignal = db.create<ProjectSignal>('project_signals', {
      reference_id: 'SIG-NEW', status: 'received', signal_type: 'repeat_client',
      source_evidence: 'Expansion task generated new opportunity from Crunch Fitness client',
      linked_client_id: 'cli-1', linked_client_name: 'Test Client',
      project_identity: 'New Gym Location', timing_signal: null,
      fit_risk_note: null, gate_outcome: 'pending', gate_decision_by: null,
      gate_decision_date: null, owner: 'marcus-johnson',
    } as Omit<ProjectSignal, db.AutoGeneratedKeys>, 'system')

    // Link signal back to expansion task
    db.update('expansion_tasks', expTask.id, {
      next_signal_created: true, next_signal_id: newSignal.id,
    }, 'system')

    // Now complete the expansion task with signal linked
    etEntity['next_signal_created'] = true
    etEntity['next_signal_id'] = newSignal.id
    etEntity['completion_outcome'] = 'Thank-you sent, new opportunity discovered'
    tr = validateTransition(expansionTaskStateMachine, {
      currentState: 'in_progress', targetState: 'complete',
      entity: etEntity, actorRoles: BD,
    })
    expect(tr.allowed).toBe(true)

    // Verify the signal exists
    const linkedSignal = db.getById<ProjectSignal>('project_signals', newSignal.id)
    expect(linkedSignal).toBeDefined()
    expect(linkedSignal!.project_identity).toBe('New Gym Location')

    // Full circle verified: project → expansion → new signal → can become new pursuit
  })
})
