/**
 * UAT Scenario 10 — No-bid and dormant recovery
 */
import { describe, it, expect, beforeEach } from 'vitest'
import * as db from '@/lib/db/json-db'
import { validateTransition } from '@/lib/state-machines/engine'
import { pursuitStateMachine } from '@/lib/state-machines/pursuit'
import type { Role } from '@/lib/permissions/roles'

const BD: Role[] = ['leadership_system_admin', 'commercial_bd']

describe('UAT Scenario 10 — No-Bid and Dormant Recovery', () => {
  beforeEach(() => { db.resetDb() })

  it('pursuit → qualification_underway → no_bid with reason', () => {
    const entity = { client_id: 'c1', project_name: 'Test', no_bid_reason: 'Out of service area' }
    // signal_received → qualification_underway
    let result = validateTransition(pursuitStateMachine, {
      currentState: 'project_signal_received', targetState: 'qualification_underway',
      entity, actorRoles: BD,
    })
    expect(result.allowed).toBe(true)

    // qualification_underway → no_bid (requires reason)
    result = validateTransition(pursuitStateMachine, {
      currentState: 'qualification_underway', targetState: 'no_bid',
      entity, actorRoles: BD, reason: 'Out of service area',
    })
    expect(result.allowed).toBe(true)
  })

  it('no_bid is terminal — cannot transition out', () => {
    const entity = { client_id: 'c1', project_name: 'Test' }
    const result = validateTransition(pursuitStateMachine, {
      currentState: 'no_bid', targetState: 'qualification_underway',
      entity, actorRoles: BD, reason: 'Revisiting',
    })
    expect(result.allowed).toBe(false)
    expect(result.errors.some(e => e.includes('terminal'))).toBe(true)
  })

  it('pursuit → hold → dormant → reactivate to qualification_underway', () => {
    const entity = { client_id: 'c1', project_name: 'Test' }

    // qualification_underway → hold
    let result = validateTransition(pursuitStateMachine, {
      currentState: 'qualification_underway', targetState: 'hold',
      entity, actorRoles: BD, reason: 'Client requested pause',
    })
    expect(result.allowed).toBe(true)

    // hold → dormant
    result = validateTransition(pursuitStateMachine, {
      currentState: 'hold', targetState: 'dormant',
      entity, actorRoles: BD, reason: 'Extended delay',
    })
    expect(result.allowed).toBe(true)

    // dormant → qualification_underway (reactivation)
    result = validateTransition(pursuitStateMachine, {
      currentState: 'dormant', targetState: 'qualification_underway',
      entity, actorRoles: BD, reason: 'Client ready to proceed',
    })
    expect(result.allowed).toBe(true)
  })

  it('all state transitions are logged in audit trail', () => {
    const pursuit = db.create('pursuits', {
      reference_id: 'PUR-0001', linked_signal_id: 'sig-1',
      project_name: 'Test', client_id: 'c1', client_name: 'Test Co',
      stage: 'project_signal_received', owner: 'system',
    } as Omit<db.BaseEntity, db.AutoGeneratedKeys> & Record<string, unknown>, 'system')

    db.update('pursuits', pursuit.id, { stage: 'qualification_underway' }, 'system', 'Advanced to qualification')
    db.update('pursuits', pursuit.id, { stage: 'hold' }, 'system', 'Client requested pause')
    db.update('pursuits', pursuit.id, { stage: 'dormant' }, 'system', 'Extended delay')
    db.update('pursuits', pursuit.id, { stage: 'qualification_underway' }, 'system', 'Reactivated — client ready')

    const audit = db.getAuditLog('pursuits', pursuit.id)
    expect(audit.length).toBeGreaterThanOrEqual(5) // create + 4 updates
    expect(audit.some(e => e.reason?.includes('Reactivated'))).toBe(true)
  })
})
