/**
 * UAT Scenario 1 — Standard accepted job to PM claim to first mobilization
 * Full lifecycle: Client → Contact → Signal → Pursuit → Estimate → Proposal → Award → Project → Mobilization
 */
import { describe, it, expect, beforeEach } from 'vitest'
import * as db from '@/lib/db/json-db'
import { validateTransition } from '@/lib/state-machines/engine'
import { clientStateMachine } from '@/lib/state-machines/client'
import { projectSignalStateMachine } from '@/lib/state-machines/project-signal'
import { pursuitStateMachine } from '@/lib/state-machines/pursuit'
import { estimateStateMachine } from '@/lib/state-machines/estimate'
import { proposalStateMachine } from '@/lib/state-machines/proposal'
import { awardHandoffStateMachine } from '@/lib/state-machines/award-handoff'
import { projectStateMachine } from '@/lib/state-machines/project'
import { mobilizationStateMachine } from '@/lib/state-machines/mobilization'
import type { Client, Contact, ProjectSignal, Pursuit, Estimate, Proposal, AwardHandoff, Project, Mobilization } from '@/types/commercial'
import type { Role } from '@/lib/permissions/roles'

const ACTOR = 'uat-tester'
const BD_ROLES: Role[] = ['leadership_system_admin', 'commercial_bd']
const PM_ROLES: Role[] = ['leadership_system_admin', 'pm_ops']
const EST_ROLES: Role[] = ['leadership_system_admin', 'estimating']

function fullChecklist() {
  return { crew_confirmed: true, equipment_loaded: true, travel_booked: true, lodging_booked: true, per_diem_approved: true, jobber_synced: true, teams_posted: true }
}

describe('UAT Scenario 1 — Full Lifecycle: Signal to Mobilization Ready', () => {
  beforeEach(() => { db.resetDb() })

  it('completes the full commercial→PM lifecycle with all gates enforced', () => {
    // 1. Create Client
    const client = db.create<Client>('clients', {
      reference_id: 'CLT-0001', name: 'UAT Builder Co', status: 'watchlist',
      tier: 'A', vertical: 'general_contractor', market: 'dallas_fort_worth',
      relationship_strength: 'cold', preferred_provider_candidate: false,
      contacts: [], owner: ACTOR,
    } as Omit<Client, db.AutoGeneratedKeys | db.DefaultableKeys>, ACTOR)
    expect(client.id).toBeDefined()

    // 2. Create Contact
    const contact = db.create<Contact>('contacts', {
      reference_id: 'CON-0001', first_name: 'Jane', last_name: 'Doe', title: 'PM',
      client_id: client.id, client_name: 'UAT Builder Co', layer: 'pm_super_field',
      influence: 'high', is_champion: false, relationship_strength: 'new',
      touch_count: 0, owner: ACTOR,
    } as Omit<Contact, db.AutoGeneratedKeys | db.DefaultableKeys>, ACTOR)
    expect(contact.id).toBeDefined()

    // 3. Create Project Signal
    const signal = db.create<ProjectSignal>('project_signals', {
      reference_id: 'SIG-0001', status: 'received', signal_type: 'direct_contact',
      source_evidence: 'Jane called about a new gym project',
      linked_client_id: client.id, linked_client_name: 'UAT Builder Co',
      linked_contact_id: contact.id, linked_contact_name: 'Jane Doe',
      project_identity: 'UAT Gym Build', timing_signal: 'Construction start Q3 2026',
      fit_risk_note: 'Good fit for BLU Standard', gate_outcome: 'pending', gate_decision_by: null,
      gate_decision_date: null, owner: ACTOR,
    } as Omit<ProjectSignal, db.AutoGeneratedKeys | db.DefaultableKeys>, ACTOR)

    // 4. Advance signal: received → under_review → passed
    let result = validateTransition(projectSignalStateMachine, {
      currentState: 'received', targetState: 'under_review',
      entity: { ...signal }, actorRoles: BD_ROLES,
    })
    expect(result.allowed).toBe(true)
    db.update('project_signals', signal.id, { status: 'under_review' }, ACTOR)

    result = validateTransition(projectSignalStateMachine, {
      currentState: 'under_review', targetState: 'passed',
      entity: { ...signal, status: 'under_review' }, actorRoles: BD_ROLES,
    })
    expect(result.allowed).toBe(true)
    db.update('project_signals', signal.id, { status: 'passed', gate_outcome: 'passed' }, ACTOR)

    // 5. Create Pursuit from passed signal
    const pursuit = db.create<Pursuit>('pursuits', {
      reference_id: 'PUR-0001', linked_signal_id: signal.id,
      project_name: 'UAT Gym Build', client_id: client.id, client_name: 'UAT Builder Co',
      stage: 'project_signal_received', signal_type: 'referral', client_type: 'gc',
      build_type: 'gym_fitness', location: 'Dallas, TX', approx_sqft: 20000,
      owner: ACTOR,
    } as Omit<Pursuit, db.AutoGeneratedKeys | db.DefaultableKeys>, ACTOR)

    // 6. Advance pursuit: signal_received → qualification_underway → qualified → precon → estimate_ready
    const pursuitEntity = { ...pursuit, client_id: client.id, project_name: 'UAT Gym Build' } as Record<string, unknown>
    const pursuitPath = [
      { from: 'project_signal_received', to: 'qualification_underway' },
      { from: 'qualification_underway', to: 'qualified_pursuit' },
      { from: 'qualified_pursuit', to: 'preconstruction_packet_open' },
      { from: 'preconstruction_packet_open', to: 'estimate_ready' },
    ]
    for (const step of pursuitPath) {
      result = validateTransition(pursuitStateMachine, {
        currentState: step.from, targetState: step.to,
        entity: pursuitEntity, actorRoles: BD_ROLES,
      })
      expect(result.allowed).toBe(true)
      pursuitEntity['stage'] = step.to
    }
    db.update('pursuits', pursuit.id, { stage: 'estimate_ready' }, ACTOR)

    // 7. Create Estimate + advance to approved_for_proposal
    const estimate = db.create<Estimate>('estimates', {
      reference_id: 'EST-0001', status: 'draft', linked_pursuit_id: pursuit.id,
      linked_client_id: client.id, linked_client_name: 'UAT Builder Co',
      linked_pursuit_name: 'UAT Gym Build', project_name: 'UAT Gym Build',
      build_type: 'gym_fitness', square_footage: 20000, stage_count: 3,
      stage_selections: [], tier_index: 3, base_rate: null, blu3_rate: null,
      surcharges: [], mobilization_cost: null, exterior_cost: null, window_cost: null,
      per_diem_cost: null, labor_target_hours: null, assumptions: 'Test',
      exclusions: null, scope_text: 'Full clean', pricing_summary: { stage_breakdowns: [], subtotal: 20000, adjustments: 0, grand_total: 20000 },
      qa_reviewer_id: 'antonio', qa_reviewer_name: 'Antonio', qa_notes: null,
      version: 1, superseded_by_id: null, estimator_snapshot: null, owner: ACTOR,
    } as Omit<Estimate, db.AutoGeneratedKeys | db.DefaultableKeys>, ACTOR)

    const estEntity = { ...estimate } as Record<string, unknown>
    // draft → in_build → qa_review → approved_for_proposal
    result = validateTransition(estimateStateMachine, { currentState: 'draft', targetState: 'in_build', entity: estEntity, actorRoles: EST_ROLES })
    expect(result.allowed).toBe(true)
    estEntity['status'] = 'in_build'
    result = validateTransition(estimateStateMachine, { currentState: 'in_build', targetState: 'qa_review', entity: estEntity, actorRoles: EST_ROLES })
    expect(result.allowed).toBe(true)
    estEntity['status'] = 'qa_review'
    result = validateTransition(estimateStateMachine, { currentState: 'qa_review', targetState: 'approved_for_proposal', entity: estEntity, actorRoles: EST_ROLES, approvalGranted: true })
    expect(result.allowed).toBe(true)
    db.update('estimates', estimate.id, { status: 'approved_for_proposal' }, ACTOR)

    // 8. Create Proposal → deliver → in_review → accepted
    const proposal = db.create<Proposal>('proposals', {
      reference_id: 'PRO-0001', status: 'delivered', linked_estimate_id: estimate.id,
      linked_pursuit_id: pursuit.id, linked_client_id: client.id,
      linked_client_name: 'UAT Builder Co', project_name: 'UAT Gym Build',
      proposal_value: 20000, version: 1, delivery_date: '2026-03-01',
      decision_target_date: '2026-03-15', accepted_rejected_reason: null,
      acceptance_confirmation_method: null, decision_cadence_next_date: null,
      external_notes: null, created_award_id: null, owner: ACTOR,
    } as Omit<Proposal, db.AutoGeneratedKeys | db.DefaultableKeys>, ACTOR)

    const propEntity = { ...proposal, decision_target_date: '2026-03-15', acceptance_confirmation_method: 'email' } as Record<string, unknown>
    result = validateTransition(proposalStateMachine, { currentState: 'delivered', targetState: 'in_review', entity: propEntity, actorRoles: BD_ROLES })
    expect(result.allowed).toBe(true)
    result = validateTransition(proposalStateMachine, { currentState: 'in_review', targetState: 'accepted', entity: propEntity, actorRoles: BD_ROLES })
    expect(result.allowed).toBe(true)
    db.update('proposals', proposal.id, { status: 'accepted', acceptance_confirmation_method: 'email' }, ACTOR)

    // 9. Create Award/Handoff → advance to closed_to_ops
    const complianceDocs = [
      { doc_name: 'COI', required: true, status: 'received', received_date: '2026-03-10', notes: null },
      { doc_name: 'W-9', required: true, status: 'received', received_date: '2026-03-10', notes: null },
    ]
    const award = db.create<AwardHandoff>('award_handoffs', {
      reference_id: 'AWD-0001', status: 'awarded_intake_open',
      linked_proposal_id: proposal.id, linked_pursuit_id: pursuit.id,
      linked_estimate_id: estimate.id, linked_client_id: client.id,
      project_name: 'UAT Gym Build', accepted_baseline_snapshot: { proposal_value: 20000 },
      compliance_tracker: complianceDocs, startup_blockers: [],
      teams_handoff_post_url: null, pm_claim_user_id: null, pm_claim_timestamp: null,
      created_project_id: null, owner: ACTOR,
    } as Omit<AwardHandoff, db.AutoGeneratedKeys | db.DefaultableKeys>, ACTOR)

    const awardEntity = { ...award } as Record<string, unknown>
    const awardPath = [
      { from: 'awarded_intake_open', to: 'compliance_in_progress' },
      { from: 'compliance_in_progress', to: 'handoff_posted' },
      { from: 'handoff_posted', to: 'pm_claimed' },
      { from: 'pm_claimed', to: 'closed_to_ops' },
    ]
    for (const step of awardPath) {
      if (step.to === 'pm_claimed') awardEntity['pm_claim_user_id'] = 'cullen'
      result = validateTransition(awardHandoffStateMachine, {
        currentState: step.from, targetState: step.to,
        entity: awardEntity, actorRoles: step.to === 'pm_claimed' ? PM_ROLES : BD_ROLES,
      })
      expect(result.allowed).toBe(true)
      awardEntity['status'] = step.to
    }
    db.update('award_handoffs', award.id, { status: 'closed_to_ops', pm_claim_user_id: 'cullen' }, ACTOR)

    // 10. Create Project
    const project = db.create<Project>('projects', {
      reference_id: 'PRJ-0001', status: 'startup_pending',
      linked_award_handoff_id: award.id, linked_client_id: client.id,
      project_name: 'UAT Gym Build', pm_owner_id: 'cullen',
      commercial_baseline_snapshot: { proposal_value: 20000 },
      client_stage_map: null, target_turnover_date: null, billing_references: null,
      active_change_order_count: 0, owner: 'cullen',
    } as Omit<Project, db.AutoGeneratedKeys | db.DefaultableKeys>, ACTOR)

    // Advance: startup_pending → forecasting_active
    const projEntity = { ...project, pm_owner_id: 'cullen' } as Record<string, unknown>
    result = validateTransition(projectStateMachine, {
      currentState: 'startup_pending', targetState: 'forecasting_active',
      entity: projEntity, actorRoles: PM_ROLES,
    })
    expect(result.allowed).toBe(true)
    db.update('projects', project.id, { status: 'forecasting_active' }, ACTOR)

    // 11. Create Mobilization → advance to ready
    const mob = db.create<Mobilization>('mobilizations', {
      reference_id: 'MOB-0001', status: 'handoff_incomplete',
      linked_project_id: project.id, linked_client_id: client.id,
      stage_name: 'Trip 1 — Rough Clean', crew_lead_id: 'lead-1',
      named_technicians: ['tech-1'], requested_start_date: '2026-05-01',
      requested_end_date: '2026-05-05', actual_start_date: null, actual_end_date: null,
      site_address: '123 Test St', access_plan: 'Badge access',
      travel_posture: 'local', lodging_details: null, per_diem_budget: null,
      equipment_checklist: [], vehicle_plan: 'Truck #1',
      readiness_checklist: fullChecklist(), compressed_planning: false,
      daily_reports: [], photo_report_link: null, client_signoff_status: null,
      qc_stage_completion: null, invoice_release_status: null,
      blocker_reason: null, blocker_owner: null, missing_items_log: null,
      actuals_notes: null, owner: 'cullen',
    } as Omit<Mobilization, db.AutoGeneratedKeys | db.DefaultableKeys>, ACTOR)

    const mobEntity = { ...mob } as Record<string, unknown>
    // handoff_incomplete → needs_planning → ready
    result = validateTransition(mobilizationStateMachine, {
      currentState: 'handoff_incomplete', targetState: 'needs_planning',
      entity: mobEntity, actorRoles: PM_ROLES,
    })
    expect(result.allowed).toBe(true)
    result = validateTransition(mobilizationStateMachine, {
      currentState: 'needs_planning', targetState: 'ready',
      entity: mobEntity, actorRoles: PM_ROLES,
    })
    expect(result.allowed).toBe(true)

    // 12. Verify audit trail
    const clientAudit = db.getAuditLog('clients', client.id)
    expect(clientAudit.length).toBeGreaterThan(0)
    const signalAudit = db.getAuditLog('project_signals', signal.id)
    expect(signalAudit.length).toBeGreaterThan(0)
    const projectAudit = db.getAuditLog('projects', project.id)
    expect(projectAudit.length).toBeGreaterThan(0)
  })

  it('blocks mobilization ready without readiness gate', () => {
    const mobEntity = {
      readiness_checklist: { crew_confirmed: false, equipment_loaded: false, travel_booked: false, lodging_booked: false, per_diem_approved: false, jobber_synced: false, teams_posted: false },
      compressed_planning: false, exception_flag: false, missing_items_log: null,
    }
    const result = validateTransition(mobilizationStateMachine, {
      currentState: 'needs_planning', targetState: 'ready',
      entity: mobEntity, actorRoles: PM_ROLES,
    })
    expect(result.allowed).toBe(false)
    expect(result.errors.some(e => e.includes('Readiness'))).toBe(true)
  })
})
