/**
 * UAT Scenario 3 — Client-caused delay after planning
 */
import { describe, it, expect, beforeEach } from 'vitest'
import * as db from '@/lib/db/json-db'
import { validateTransition } from '@/lib/state-machines/engine'
import { mobilizationStateMachine } from '@/lib/state-machines/mobilization'
import type { Role } from '@/lib/permissions/roles'

const PM: Role[] = ['leadership_system_admin', 'pm_ops']
function fullChecklist() {
  return { crew_confirmed: true, equipment_loaded: true, travel_booked: true, lodging_booked: true, per_diem_approved: true, jobber_synced: true, teams_posted: true }
}

describe('UAT Scenario 3 — Client-Caused Delay', () => {
  beforeEach(() => { db.resetDb() })

  it('blocks mobilization, preserves baseline, resolves and returns to ready', () => {
    // Create project with baseline
    const project = db.create('projects', {
      reference_id: 'PRJ-0001', status: 'execution_active',
      linked_award_handoff_id: 'awd-1', linked_client_id: 'cli-1',
      project_name: 'Test', pm_owner_id: 'cullen',
      commercial_baseline_snapshot: { proposal_value: 25000, scope: 'original' },
      client_stage_map: null, target_turnover_date: null, billing_references: null,
      active_change_order_count: 0, owner: 'cullen',
    } as Omit<db.BaseEntity, db.AutoGeneratedKeys | db.DefaultableKeys> & Record<string, unknown>, 'system')

    // Ready → blocked
    const entity = {
      readiness_checklist: fullChecklist(), blocker_reason: 'Client delayed access',
      blocker_owner: 'client-pm', missing_items_log: null, compressed_planning: false, exception_flag: false,
    }
    let result = validateTransition(mobilizationStateMachine, {
      currentState: 'ready', targetState: 'blocked', entity, actorRoles: PM,
    })
    expect(result.allowed).toBe(true)

    // Verify baseline untouched
    const updatedProject = db.getById('projects', project.id) as Record<string, unknown>
    expect((updatedProject['commercial_baseline_snapshot'] as Record<string, unknown>)['proposal_value']).toBe(25000)

    // Blocked → needs_planning (resolve)
    result = validateTransition(mobilizationStateMachine, {
      currentState: 'blocked', targetState: 'needs_planning', entity, actorRoles: PM,
      reason: 'Client provided access',
    })
    expect(result.allowed).toBe(true)

    // needs_planning → ready (return to ready)
    result = validateTransition(mobilizationStateMachine, {
      currentState: 'needs_planning', targetState: 'ready', entity, actorRoles: PM,
    })
    expect(result.allowed).toBe(true)
  })
})
