/**
 * UAT Scenario 5 — Multi-stage project with repeat trips
 */
import { describe, it, expect, beforeEach } from 'vitest'
import * as db from '@/lib/db/json-db'
import { validateTransition } from '@/lib/state-machines/engine'
import { projectStateMachine } from '@/lib/state-machines/project'
import { mobilizationStateMachine } from '@/lib/state-machines/mobilization'
import type { Role } from '@/lib/permissions/roles'

const PM: Role[] = ['leadership_system_admin', 'pm_ops']

function fullChecklist() {
  return { crew_confirmed: true, equipment_loaded: true, travel_booked: true, lodging_booked: true, per_diem_approved: true, jobber_synced: true, teams_posted: true }
}

function completionEntity() {
  return {
    readiness_checklist: fullChecklist(), actual_start_date: '2026-05-01',
    photo_report_link: 'https://sharepoint/photos', client_signoff_status: 'obtained',
    qc_stage_completion: { passed: true, reviewer_id: 'cullen', date: '2026-05-05', notes: 'OK' },
    blocker_reason: null, blocker_owner: null, missing_items_log: null,
    compressed_planning: false, exception_flag: false,
  }
}

describe('UAT Scenario 5 — Multi-Stage Project', () => {
  beforeEach(() => { db.resetDb() })

  it('completes 2 trips, cancels 1, and reaches operationally_complete', () => {
    const project = db.create('projects', {
      reference_id: 'PRJ-0001', status: 'execution_active',
      linked_award_handoff_id: 'awd-1', linked_client_id: 'cli-1',
      project_name: 'Multi-stage', pm_owner_id: 'cullen',
      commercial_baseline_snapshot: {}, client_stage_map: null,
      target_turnover_date: null, billing_references: null,
      active_change_order_count: 0, owner: 'cullen',
    } as Omit<db.BaseEntity, db.AutoGeneratedKeys | db.DefaultableKeys> & Record<string, unknown>, 'system')

    // Create 3 mobilizations
    for (let i = 1; i <= 3; i++) {
      db.create('mobilizations', {
        reference_id: `MOB-000${i}`, status: 'complete' as string,
        linked_project_id: project.id, linked_client_id: 'cli-1',
        stage_name: `Trip ${i}`, owner: 'cullen',
        readiness_checklist: fullChecklist(),
      } as Omit<db.BaseEntity, db.AutoGeneratedKeys | db.DefaultableKeys> & Record<string, unknown>, 'system')
    }

    // Cancel Trip 3
    const mobs = db.list('mobilizations') as (db.BaseEntity & Record<string, unknown>)[]
    const trip3 = mobs.find(m => m['reference_id'] === 'MOB-0003')!
    db.update('mobilizations', trip3.id, { status: 'cancelled' }, 'system')

    // Verify project can reach operationally_complete (0 open mobs)
    const allMobs = db.list('mobilizations') as (db.BaseEntity & Record<string, unknown>)[]
    const openMobs = allMobs.filter(m => !['complete', 'cancelled'].includes(m['status'] as string))
    expect(openMobs.length).toBe(0)

    const projEntity = { ...project, mobilization_count: 3, open_mobilization_count: 0 } as Record<string, unknown>
    const result = validateTransition(projectStateMachine, {
      currentState: 'execution_active', targetState: 'operationally_complete',
      entity: projEntity, actorRoles: PM,
    })
    expect(result.allowed).toBe(true)
  })

  it('blocks operationally_complete when open mobilizations remain', () => {
    const projEntity = { mobilization_count: 3, open_mobilization_count: 1 }
    const result = validateTransition(projectStateMachine, {
      currentState: 'execution_active', targetState: 'operationally_complete',
      entity: projEntity, actorRoles: PM,
    })
    expect(result.allowed).toBe(false)
  })

  it('completed mobilization cannot be reopened (terminal)', () => {
    const result = validateTransition(mobilizationStateMachine, {
      currentState: 'complete', targetState: 'needs_planning',
      entity: completionEntity(), actorRoles: PM,
    })
    expect(result.allowed).toBe(false)
    expect(result.errors.some(e => e.includes('terminal'))).toBe(true)
  })
})
