import { describe, it, expect, beforeEach } from 'vitest'
import { resetDb } from '@/lib/db/json-db'
import * as mobilizationDb from '@/lib/db/mobilizations'
import * as projectDb from '@/lib/db/projects'
import * as db from '@/lib/db/json-db'
import type { Project, Mobilization, ReadinessChecklist } from '@/types/commercial'

function seedTestProject(): Project {
  return projectDb.createProject(
    {
      linked_award_handoff_id: 'awd-test',
      linked_client_id: 'clt-test',
      project_name: 'Test Project',
      pm_owner_id: 'cullen',
      commercial_baseline_snapshot: {},
      client_stage_map: null,
      target_turnover_date: null,
      billing_references: null,
      active_change_order_count: 0,
      owner: 'cullen',
    } as Omit<Project, db.AutoGeneratedKeys | 'reference_id' | 'status'>,
    'test-actor',
  )
}

const defaultChecklist: ReadinessChecklist = {
  crew_confirmed: false,
  equipment_loaded: false,
  travel_booked: false,
  lodging_booked: false,
  per_diem_approved: false,
  jobber_synced: false,
  teams_posted: false,
}

function makeMobData(projectId: string): Omit<Mobilization, db.AutoGeneratedKeys | 'reference_id' | 'status'> {
  return {
    linked_project_id: projectId,
    linked_client_id: 'clt-test',
    stage_name: 'Trip 1 — Rough Clean',
    crew_lead_id: null,
    named_technicians: [],
    requested_start_date: null,
    requested_end_date: null,
    actual_start_date: null,
    actual_end_date: null,
    site_address: null,
    access_plan: null,
    travel_posture: 'local',
    lodging_details: null,
    per_diem_budget: null,
    equipment_checklist: [],
    vehicle_plan: null,
    readiness_checklist: defaultChecklist,
    compressed_planning: false,
    daily_reports: [],
    photo_report_link: null,
    client_signoff_status: null,
    qc_stage_completion: null,
    invoice_release_status: null,
    blocker_reason: null,
    blocker_owner: null,
    missing_items_log: null,
    actuals_notes: null,
    owner: 'cullen',
  } as Omit<Mobilization, db.AutoGeneratedKeys | 'reference_id' | 'status'>
}

describe('Mobilization Data Access Layer', () => {
  beforeEach(() => {
    resetDb()
  })

  it('creates a mobilization with MOB-XXXX reference_id', () => {
    const project = seedTestProject()
    const mob = mobilizationDb.createMobilization(makeMobData(project.id), 'test-actor')
    expect(mob.reference_id).toBe('MOB-0001')
    expect(mob.status).toBe('handoff_incomplete')
    expect(mob.linked_project_id).toBe(project.id)
  })

  it('generates sequential reference IDs', () => {
    const project = seedTestProject()
    const mob1 = mobilizationDb.createMobilization(makeMobData(project.id), 'test-actor')
    const mob2 = mobilizationDb.createMobilization(
      { ...makeMobData(project.id), stage_name: 'Trip 2' },
      'test-actor',
    )
    expect(mob1.reference_id).toBe('MOB-0001')
    expect(mob2.reference_id).toBe('MOB-0002')
  })

  it('gets a mobilization by ID', () => {
    const project = seedTestProject()
    const mob = mobilizationDb.createMobilization(makeMobData(project.id), 'test-actor')
    const fetched = mobilizationDb.getMobilization(mob.id)
    expect(fetched).toBeDefined()
    expect(fetched!.id).toBe(mob.id)
  })

  it('lists all mobilizations', () => {
    const project = seedTestProject()
    mobilizationDb.createMobilization(makeMobData(project.id), 'test-actor')
    mobilizationDb.createMobilization(
      { ...makeMobData(project.id), stage_name: 'Trip 2' },
      'test-actor',
    )
    const all = mobilizationDb.listMobilizations()
    expect(all.length).toBe(2)
  })

  it('lists mobilizations by project', () => {
    const project1 = seedTestProject()
    const project2 = projectDb.createProject(
      {
        linked_award_handoff_id: 'awd-test-2',
        linked_client_id: 'clt-test',
        project_name: 'Test Project 2',
        pm_owner_id: 'cullen',
        commercial_baseline_snapshot: {},
        client_stage_map: null,
        target_turnover_date: null,
        billing_references: null,
        active_change_order_count: 0,
        owner: 'cullen',
      } as Omit<Project, db.AutoGeneratedKeys | 'reference_id' | 'status'>,
      'test-actor',
    )
    mobilizationDb.createMobilization(makeMobData(project1.id), 'test-actor')
    mobilizationDb.createMobilization(makeMobData(project2.id), 'test-actor')

    const p1Mobs = mobilizationDb.listMobilizationsByProject(project1.id)
    expect(p1Mobs.length).toBe(1)
    expect(p1Mobs[0]!.linked_project_id).toBe(project1.id)
  })

  it('updates a mobilization', () => {
    const project = seedTestProject()
    const mob = mobilizationDb.createMobilization(makeMobData(project.id), 'test-actor')
    const updated = mobilizationDb.updateMobilization(
      mob.id,
      { crew_lead_id: 'marcus-johnson' },
      'test-actor',
    )
    expect(updated.crew_lead_id).toBe('marcus-johnson')
  })

  it('archives a mobilization (soft delete)', () => {
    const project = seedTestProject()
    const mob = mobilizationDb.createMobilization(makeMobData(project.id), 'test-actor')
    mobilizationDb.archiveMobilization(mob.id, 'test-actor', 'No longer needed')
    const fetched = mobilizationDb.getMobilization(mob.id)
    expect(fetched).toBeUndefined()
  })

  it('produces audit log entries', () => {
    const project = seedTestProject()
    const mob = mobilizationDb.createMobilization(makeMobData(project.id), 'test-actor')
    mobilizationDb.updateMobilization(mob.id, { crew_lead_id: 'tech-1' }, 'test-actor', 'Assigned lead')
    const log = mobilizationDb.getMobilizationAuditLog(mob.id)
    expect(log.length).toBe(2) // create + update
  })
})
