import { describe, it, expect, beforeEach } from 'vitest'
import { resetDb } from '@/lib/db/json-db'
import * as db from '@/lib/db/json-db'
import * as projectDb from '@/lib/db/projects'
import * as mobilizationDb from '@/lib/db/mobilizations'
import {
  createMobilizationAction,
  transitionMobilizationAction,
  addDailyReportAction,
  updateReadinessChecklistAction,
  compressedPlanningOverrideAction,
} from '@/actions/mobilization'
import type { Project, Mobilization, ReadinessChecklist } from '@/types/commercial'

const defaultChecklist: ReadinessChecklist = {
  crew_confirmed: false,
  equipment_loaded: false,
  travel_booked: false,
  lodging_booked: false,
  per_diem_approved: false,
  jobber_synced: false,
  teams_posted: false,
}

function seedTestProject(): Project {
  const project = projectDb.createProject(
    {
      linked_award_handoff_id: 'awd-test',
      linked_client_id: 'clt-test',
      project_name: 'Test Project',
      pm_owner_id: 'cullen',
      commercial_baseline_snapshot: {},
      client_stage_map: null,
      target_turnover_date: null,
      billing_references: null,
      active_change_order_count: 0,
      owner: 'cullen',
    } as Omit<Project, db.AutoGeneratedKeys | 'reference_id' | 'status'>,
    'test-actor',
  )
  // Projects start as startup_pending; advance to forecasting_active for mobilization creation
  return projectDb.updateProject(project.id, { status: 'forecasting_active' } as Record<string, unknown>, 'test-actor') as Project
}

function makeCreateInput(projectId: string) {
  return {
    linked_project_id: projectId,
    linked_client_id: 'clt-test',
    stage_name: 'Trip 1 — Rough Clean',
  }
}

describe('Mobilization Server Actions — Create', () => {
  beforeEach(() => {
    resetDb()
  })

  it('creates mobilization when project is forecasting_active', async () => {
    const project = seedTestProject()
    const result = await createMobilizationAction(makeCreateInput(project.id))
    expect(result.success).toBe(true)
    expect(result.data?.status).toBe('handoff_incomplete')
    expect(result.data?.reference_id).toBe('MOB-0001')
  })

  it('creates mobilization when project is execution_active', async () => {
    const project = seedTestProject()
    projectDb.updateProject(project.id, { status: 'execution_active' } as Record<string, unknown>, 'test')
    const result = await createMobilizationAction(makeCreateInput(project.id))
    expect(result.success).toBe(true)
  })

  it('blocks creation when project is startup_pending', async () => {
    const project = seedTestProject()
    // Project starts as startup_pending, then createProject sets it... actually let's update it
    projectDb.updateProject(project.id, { status: 'startup_pending' } as Record<string, unknown>, 'test')
    const result = await createMobilizationAction(makeCreateInput(project.id))
    expect(result.success).toBe(false)
    expect(result.error).toContain('forecasting_active or execution_active')
  })

  it('blocks creation when project is operationally_complete', async () => {
    const project = seedTestProject()
    projectDb.updateProject(project.id, { status: 'operationally_complete' } as Record<string, unknown>, 'test')
    const result = await createMobilizationAction(makeCreateInput(project.id))
    expect(result.success).toBe(false)
  })

  it('blocks creation with non-existent project', async () => {
    const result = await createMobilizationAction(makeCreateInput('non-existent'))
    expect(result.success).toBe(false)
    expect(result.error).toContain('not found')
  })
})

describe('Mobilization Server Actions — Transition', () => {
  beforeEach(() => {
    resetDb()
  })

  it('transitions handoff_incomplete → needs_planning', async () => {
    const project = seedTestProject()
    const mob = mobilizationDb.createMobilization(
      {
        linked_project_id: project.id,
        linked_client_id: 'clt-test',
        stage_name: 'Trip 1',
        crew_lead_id: null,
        named_technicians: [],
        requested_start_date: null,
        requested_end_date: null,
        actual_start_date: null,
        actual_end_date: null,
        site_address: null,
        access_plan: null,
        travel_posture: 'local',
        lodging_details: null,
        per_diem_budget: null,
        equipment_checklist: [],
        vehicle_plan: null,
        readiness_checklist: defaultChecklist,
        compressed_planning: false,
        daily_reports: [],
        photo_report_link: null,
        client_signoff_status: null,
        qc_stage_completion: null,
        invoice_release_status: null,
        blocker_reason: null,
        blocker_owner: null,
        missing_items_log: null,
        actuals_notes: null,
        owner: 'cullen',
      } as Omit<Mobilization, db.AutoGeneratedKeys | 'reference_id' | 'status'>,
      'test-actor',
    )

    const result = await transitionMobilizationAction({
      mobilization_id: mob.id,
      target_status: 'needs_planning',
    })
    expect(result.success).toBe(true)
    expect(result.data?.status).toBe('needs_planning')
  })
})

describe('Mobilization Server Actions — Daily Reports', () => {
  beforeEach(() => {
    resetDb()
  })

  it('adds a daily report', async () => {
    const project = seedTestProject()
    const mob = mobilizationDb.createMobilization(
      {
        linked_project_id: project.id,
        linked_client_id: 'clt-test',
        stage_name: 'Trip 1',
        crew_lead_id: null,
        named_technicians: [],
        requested_start_date: null,
        requested_end_date: null,
        actual_start_date: null,
        actual_end_date: null,
        site_address: null,
        access_plan: null,
        travel_posture: 'local',
        lodging_details: null,
        per_diem_budget: null,
        equipment_checklist: [],
        vehicle_plan: null,
        readiness_checklist: defaultChecklist,
        compressed_planning: false,
        daily_reports: [],
        photo_report_link: null,
        client_signoff_status: null,
        qc_stage_completion: null,
        invoice_release_status: null,
        blocker_reason: null,
        blocker_owner: null,
        missing_items_log: null,
        actuals_notes: null,
        owner: 'cullen',
      } as Omit<Mobilization, db.AutoGeneratedKeys | 'reference_id' | 'status'>,
      'test-actor',
    )

    const result = await addDailyReportAction({
      mobilization_id: mob.id,
      date: '2026-04-07',
      summary: 'Completed rough clean of floors 1-3',
      photos: [],
      exceptions: null,
    })
    expect(result.success).toBe(true)
    expect(result.data?.daily_reports.length).toBe(1)
    expect(result.data?.daily_reports[0]?.summary).toBe('Completed rough clean of floors 1-3')
  })
})

describe('Mobilization Server Actions — Readiness Checklist', () => {
  beforeEach(() => {
    resetDb()
  })

  it('updates readiness checklist', async () => {
    const project = seedTestProject()
    const mob = mobilizationDb.createMobilization(
      {
        linked_project_id: project.id,
        linked_client_id: 'clt-test',
        stage_name: 'Trip 1',
        crew_lead_id: null,
        named_technicians: [],
        requested_start_date: null,
        requested_end_date: null,
        actual_start_date: null,
        actual_end_date: null,
        site_address: null,
        access_plan: null,
        travel_posture: 'local',
        lodging_details: null,
        per_diem_budget: null,
        equipment_checklist: [],
        vehicle_plan: null,
        readiness_checklist: defaultChecklist,
        compressed_planning: false,
        daily_reports: [],
        photo_report_link: null,
        client_signoff_status: null,
        qc_stage_completion: null,
        invoice_release_status: null,
        blocker_reason: null,
        blocker_owner: null,
        missing_items_log: null,
        actuals_notes: null,
        owner: 'cullen',
      } as Omit<Mobilization, db.AutoGeneratedKeys | 'reference_id' | 'status'>,
      'test-actor',
    )

    const result = await updateReadinessChecklistAction({
      mobilization_id: mob.id,
      checklist: {
        crew_confirmed: true,
        equipment_loaded: true,
        travel_booked: true,
        lodging_booked: true,
        per_diem_approved: true,
        jobber_synced: false,
        teams_posted: false,
      },
    })
    expect(result.success).toBe(true)
    expect(result.data?.readiness_checklist.crew_confirmed).toBe(true)
    expect(result.data?.readiness_checklist.equipment_loaded).toBe(true)
  })
})

describe('Mobilization Server Actions — Compressed Planning', () => {
  beforeEach(() => {
    resetDb()
  })

  it('sets compressed planning flags', async () => {
    const project = seedTestProject()
    const mob = mobilizationDb.createMobilization(
      {
        linked_project_id: project.id,
        linked_client_id: 'clt-test',
        stage_name: 'Trip 1',
        crew_lead_id: null,
        named_technicians: [],
        requested_start_date: null,
        requested_end_date: null,
        actual_start_date: null,
        actual_end_date: null,
        site_address: null,
        access_plan: null,
        travel_posture: 'local',
        lodging_details: null,
        per_diem_budget: null,
        equipment_checklist: [],
        vehicle_plan: null,
        readiness_checklist: defaultChecklist,
        compressed_planning: false,
        daily_reports: [],
        photo_report_link: null,
        client_signoff_status: null,
        qc_stage_completion: null,
        invoice_release_status: null,
        blocker_reason: null,
        blocker_owner: null,
        missing_items_log: null,
        actuals_notes: null,
        owner: 'cullen',
      } as Omit<Mobilization, db.AutoGeneratedKeys | 'reference_id' | 'status'>,
      'test-actor',
    )

    const result = await compressedPlanningOverrideAction({
      mobilization_id: mob.id,
      reason: 'Urgent deployment needed',
    })
    expect(result.success).toBe(true)
    expect(result.data?.compressed_planning).toBe(true)
    expect(result.data?.exception_flag).toBe(true)
  })
})
